const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.Action_Event1_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Action_Event111_Act3,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.JavaScriptInEvents.Buttons_Event37_Act1,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Behaviors.DragnDrop.Acts.SetAxes,
		C3.Plugins.System.Cnds.Every,
		C3.JavaScriptInEvents.Start_Event16_Act3,
		C3.JavaScriptInEvents.Start_Event17_Act3
	];
};
self.C3_JsPropNameTable = [
	{Bagr: 0},
	{CellBagr: 0},
	{BagrCellOne: 0},
	{Твинанимация: 0},
	{Bagr_Win: 0},
	{Bagr_PsLWin: 0},
	{Bagr_Help: 0},
	{Bagr_Two: 0},
	{Browser: 0},
	{Sound: 0},
	{LocalHost: 0},
	{Touch: 0},
	{Color: 0},
	{Act: 0},
	{Size: 0},
	{Pozis: 0},
	{BlocksDellStopUp: 0},
	{DellBlockTop_One: 0},
	{DellBlockTop_Two: 0},
	{DellBlockTop_Three: 0},
	{BlocksDellStopLeft: 0},
	{DellBlock_Left_One: 0},
	{DellBlock_Left_Two: 0},
	{DellBlock_Left_Three: 0},
	{DellBlockBottom_One: 0},
	{DellBlockBottom_Two: 0},
	{DellBlockBottom_Three: 0},
	{PdlDell: 0},
	{ActToch: 0},
	{MinusX: 0},
	{Arrows: 0},
	{ActFind: 0},
	{ActArrow: 0},
	{Name_Block: 0},
	{MinusY: 0},
	{BlocksFourA: 0},
	{Blocks_One: 0},
	{UID_Block: 0},
	{BlockPdl: 0},
	{BlocksTwoHor: 0},
	{BlocksTwoVer: 0},
	{BlocksCross: 0},
	{BlocksSquare: 0},
	{BlocksThreeOne: 0},
	{BlocksThreeTwo: 0},
	{BlocksThreeThree: 0},
	{BlocksThreeFour: 0},
	{BlocksFourThreeB: 0},
	{BlocksFourThreeC: 0},
	{BlocksFourThreeD: 0},
	{BlocksFourThreeEigth: 0},
	{BlocksFourThreeFive: 0},
	{BlocksFourThreeOne: 0},
	{BlocksFourThreeSeven: 0},
	{BlocksFourThreeSixe: 0},
	{BlocksFourThreeTen: 0},
	{wall: 0},
	{Block_Collision: 0},
	{CollisionBlock: 0},
	{Btn_Start: 0},
	{Block_UID: 0},
	{Btn_Settings: 0},
	{Btn_Restrt: 0},
	{Btn_Bomba: 0},
	{Btn_Multy: 0},
	{Btn_Reward: 0},
	{Name: 0},
	{Btn_Crestic: 0},
	{ID: 0},
	{Btn_Priz: 0},
	{Trig: 0},
	{Btn_ReArrows: 0},
	{Text_Bid: 0},
	{Text_Dimand: 0},
	{Text_HeaderSetting: 0},
	{Text_Help: 0},
	{Text_Music: 0},
	{Text_NextLevel: 0},
	{Text_PricePriz: 0},
	{Text_Priz: 0},
	{Text_RewardProgress: 0},
	{Text_Sound: 0},
	{Text_StartMenu: 0},
	{Table_Dimand: 0},
	{Bit: 0},
	{NameIcon: 0},
	{Table_Sale: 0},
	{Table_Score: 0},
	{TableBagr_Setting: 0},
	{Header_Setting: 0},
	{DragDrop: 0},
	{Sprite: 0},
	{Diamonds: 0},
	{Поворот: 0},
	{LoudTwo: 0},
	{Синусоид: 0},
	{Louder_Icon: 0},
	{NameGame: 0},
	{Finger: 0},
	{Btn_Soc: 0},
	{Btn_VK: 0},
	{Твёрдый: 0},
	{BlockDell_Famaly: 0},
	{Перетаскивание: 0},
	{Block_Famaly: 0},
	{Btn_Up: 0},
	{BtnBott: 0},
	{Btn_StartMenu: 0},
	{Music: 0},
	{Priz: 0},
	{PrizTwo: 0},
	{ReklSound: 0},
	{Score: 0},
	{Level: 0},
	{levt: 0},
	{Education: 0},
	{MultyColor: 0},
	{Vkladla: 0},
	{prevX: 0},
	{prevY: 0},
	{dx: 0},
	{dy: 0},
	{cnt: 0},
	{AcPozisBlockDell: 0},
	{AcArrowsPozis: 0},
	{AcArrowsArr: 0},
	{ActTochUp: 0},
	{ActBlockOut: 0},
	{AcTochtBlock: 0},
	{ActTochBtn: 0},
	{AcTochtBlockDell: 0},
	{ActTochCrestic: 0},
	{ActTochBtnSetting: 0},
	{SoundAct: 0},
	{SoundVsix: 0},
	{MusicAct: 0},
	{Focus: 0},
	{ActTochBomb: 0},
	{ActTochBombTwo: 0},
	{ActTochMylti: 0},
	{ActTochMyltiTwo: 0},
	{ActTochArrowsEff: 0},
	{ActTochBlockBlock: 0},
	{ActCollusion: 0},
	{ActCollusionTwo: 0},
	{ActCollusionThree: 0},
	{ActReclama: 0},
	{ActBlockCollision: 0},
	{ActBlockCollisionDell: 0},
	{Lang_Ynd: 0},
	{lang: 0},
	{screen: 0},
	{itm: 0},
	{Louder: 0},
	{Abd: 0}
];

self.InstanceType = {
	Bagr: class extends self.ISpriteInstance {},
	CellBagr: class extends self.ISpriteInstance {},
	BagrCellOne: class extends self.ISpriteInstance {},
	Bagr_Win: class extends self.ISpriteInstance {},
	Bagr_PsLWin: class extends self.ISpriteInstance {},
	Bagr_Help: class extends self.ISpriteInstance {},
	Bagr_Two: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	LocalHost: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BlocksDellStopUp: class extends self.ISpriteInstance {},
	DellBlockTop_One: class extends self.ISpriteInstance {},
	DellBlockTop_Two: class extends self.ISpriteInstance {},
	DellBlockTop_Three: class extends self.ISpriteInstance {},
	BlocksDellStopLeft: class extends self.ISpriteInstance {},
	DellBlock_Left_One: class extends self.ISpriteInstance {},
	DellBlock_Left_Two: class extends self.ISpriteInstance {},
	DellBlock_Left_Three: class extends self.ISpriteInstance {},
	DellBlockBottom_One: class extends self.ISpriteInstance {},
	DellBlockBottom_Two: class extends self.ISpriteInstance {},
	DellBlockBottom_Three: class extends self.ISpriteInstance {},
	PdlDell: class extends self.ISpriteInstance {},
	BlocksFourA: class extends self.ISpriteInstance {},
	Blocks_One: class extends self.ISpriteInstance {},
	BlockPdl: class extends self.ISpriteInstance {},
	BlocksTwoHor: class extends self.ISpriteInstance {},
	BlocksTwoVer: class extends self.ISpriteInstance {},
	BlocksCross: class extends self.ISpriteInstance {},
	BlocksSquare: class extends self.ISpriteInstance {},
	BlocksThreeOne: class extends self.ISpriteInstance {},
	BlocksThreeTwo: class extends self.ISpriteInstance {},
	BlocksThreeThree: class extends self.ISpriteInstance {},
	BlocksThreeFour: class extends self.ISpriteInstance {},
	BlocksFourThreeB: class extends self.ISpriteInstance {},
	BlocksFourThreeC: class extends self.ISpriteInstance {},
	BlocksFourThreeD: class extends self.ISpriteInstance {},
	BlocksFourThreeEigth: class extends self.ISpriteInstance {},
	BlocksFourThreeFive: class extends self.ISpriteInstance {},
	BlocksFourThreeOne: class extends self.ISpriteInstance {},
	BlocksFourThreeSeven: class extends self.ISpriteInstance {},
	BlocksFourThreeSixe: class extends self.ISpriteInstance {},
	BlocksFourThreeTen: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	Block_Collision: class extends self.ISpriteInstance {},
	CollisionBlock: class extends self.ISpriteInstance {},
	Btn_Start: class extends self.ISpriteInstance {},
	Arrows: class extends self.ISpriteInstance {},
	Btn_Settings: class extends self.ISpriteInstance {},
	Btn_Restrt: class extends self.ISpriteInstance {},
	Btn_Bomba: class extends self.ISpriteInstance {},
	Btn_Multy: class extends self.ISpriteInstance {},
	Btn_Reward: class extends self.ISpriteInstance {},
	Btn_Crestic: class extends self.ISpriteInstance {},
	Btn_Priz: class extends self.ISpriteInstance {},
	Trig: class extends self.ISpriteInstance {},
	Btn_ReArrows: class extends self.ISpriteInstance {},
	Text_Bid: class extends self.ITextInstance {},
	Text_Dimand: class extends self.ITextInstance {},
	Text_HeaderSetting: class extends self.ITextInstance {},
	Text_Help: class extends self.ITextInstance {},
	Text_Music: class extends self.ITextInstance {},
	Text_NextLevel: class extends self.ITextInstance {},
	Text_PricePriz: class extends self.ITextInstance {},
	Text_Priz: class extends self.ITextInstance {},
	Text_RewardProgress: class extends self.ITextInstance {},
	Text_Sound: class extends self.ITextInstance {},
	Text_StartMenu: class extends self.ITextInstance {},
	Table_Dimand: class extends self.ISpriteInstance {},
	Table_Sale: class extends self.ISpriteInstance {},
	Table_Score: class extends self.ISpriteInstance {},
	TableBagr_Setting: class extends self.ISpriteInstance {},
	Header_Setting: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Diamonds: class extends self.ISpriteInstance {},
	LoudTwo: class extends self.ISpriteInstance {},
	Louder_Icon: class extends self.ISpriteInstance {},
	NameGame: class extends self.ISpriteInstance {},
	Finger: class extends self.ISpriteInstance {},
	Btn_Soc: class extends self.ISpriteInstance {},
	Btn_VK: class extends self.ISpriteInstance {},
	BlockDell_Famaly: class extends self.ISpriteInstance {},
	Block_Famaly: class extends self.ISpriteInstance {},
	Btn_Up: class extends self.ISpriteInstance {},
	BtnBott: class extends self.ISpriteInstance {},
	Btn_StartMenu: class extends self.ISpriteInstance {}
}