const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Audio.Acts.PreloadByName,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.For,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.JavaScriptInEvents.Action_Event540_Act13,
		C3.Plugins.System.Acts.SubVar,
		C3.JavaScriptInEvents.Action_Event553_Act2,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Particles.Acts.SetSizeRandomiser,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.JavaScriptInEvents.Action_Event828_Act2,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.JavaScriptInEvents.Btns_Event42_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Btns_Event104_Act1,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.JavaScriptInEvents.Inventary_Event17_Act1,
		C3.JavaScriptInEvents.Inventary_Event23_Act4,
		C3.JavaScriptInEvents.Inventary_Event23_Act6,
		C3.JavaScriptInEvents.Inventary_Event76_Act3,
		C3.JavaScriptInEvents.Inventary_Event77_Act3,
		C3.JavaScriptInEvents.Inventary_Event79_Act1,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.JavaScriptInEvents.Inventary_Event124_Act1,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.JavaScriptInEvents.Inventary_Event244_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.JavaScriptInEvents.Louder_Event2_Act2
	];
};
self.C3_JsPropNameTable = [
	{ActTochEmeny: 0},
	{Твинанимация: 0},
	{Hero: 0},
	{СледитьЗа: 0},
	{Camera: 0},
	{ActJump: 0},
	{Платформер: 0},
	{PlayerCollision: 0},
	{ID: 0},
	{NameHero: 0},
	{HeroHome: 0},
	{HeroDead: 0},
	{Bagr: 0},
	{Bagr_Win: 0},
	{Bagr_WinSetting: 0},
	{Bagr_Inventary: 0},
	{Bagr_Help: 0},
	{BagrTop: 0},
	{BagrBottom: 0},
	{Sky_Nigth: 0},
	{SkyDark: 0},
	{Star: 0},
	{Platform_One: 0},
	{Platform_Two: 0},
	{Act: 0},
	{Life: 0},
	{Grass: 0},
	{Platform_TwoBlack: 0},
	{PlatformDop: 0},
	{BlackBlock_bagr: 0},
	{BlockOneBok: 0},
	{BlockOneTitle: 0},
	{Shadow: 0},
	{Синусоида: 0},
	{Palka: 0},
	{Поворот: 0},
	{Saw: 0},
	{Твёрдый: 0},
	{BlockPdl: 0},
	{СквознаяПлатформа: 0},
	{PlatformaScvoz: 0},
	{Platform_ThreeBlack: 0},
	{BlockIron: 0},
	{BlockFall: 0},
	{Ocean: 0},
	{OceanPDL: 0},
	{OceanMount: 0},
	{Синусоида2: 0},
	{OceanSin: 0},
	{BrickWall: 0},
	{BrickWallTitles: 0},
	{BrickWallTwo: 0},
	{Blocks_stoun: 0},
	{val: 0},
	{valx: 0},
	{Spring: 0},
	{Твердый: 0},
	{Blocks_sandDark: 0},
	{Block_Lava: 0},
	{LavaCollision: 0},
	{CurY: 0},
	{PeakLift: 0},
	{PeakLiftPdl: 0},
	{Btn_Sound: 0},
	{Btn_Pause: 0},
	{Btn_PauseСontinue: 0},
	{Btn_Next: 0},
	{Btn_Inventory: 0},
	{Btn_Skip: 0},
	{Btn_Again: 0},
	{ActNotToch: 0},
	{NamePage: 0},
	{Btn_GunChange: 0},
	{Btn_Figth: 0},
	{Btn_FaceHero: 0},
	{Btn_HeroGun: 0},
	{Btn_Reward: 0},
	{Btn_StartGame: 0},
	{Btn_Crestic: 0},
	{Btn_Arrow: 0},
	{Name: 0},
	{Price: 0},
	{Btn_Buy: 0},
	{BtnBottom_Pdl: 0},
	{Vbtn_up: 0},
	{BtnMob_Left: 0},
	{BtnMob_Rigth: 0},
	{Touch: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Sound: 0},
	{LocalHost: 0},
	{device: 0},
	{Mouse: 0},
	{Strong: 0},
	{ActFigth: 0},
	{Sword: 0},
	{Sloy: 0},
	{Gun_Btn: 0},
	{Onion: 0},
	{UID_Pdl: 0},
	{Peaks: 0},
	{UID_Pickes: 0},
	{Onion_Arrow: 0},
	{ActP: 0},
	{UI: 0},
	{Пуля: 0},
	{PeakPdl: 0},
	{ArrowPdl: 0},
	{Bulova: 0},
	{Thor: 0},
	{AxeV: 0},
	{AxePdl: 0},
	{ActBorn: 0},
	{Recoil: 0},
	{Guns: 0},
	{Прикрепить: 0},
	{Flame_Gun: 0},
	{Plr: 0},
	{Bulet: 0},
	{Raketa: 0},
	{PrtclSmook: 0},
	{Smook: 0},
	{BoomRak: 0},
	{SwordPirate: 0},
	{BuletPirate: 0},
	{BoomZombi: 0},
	{Spear: 0},
	{SpearPDL: 0},
	{AxeG: 0},
	{Throm: 0},
	{Portal: 0},
	{SqureYellowe: 0},
	{Portal_Particles: 0},
	{Portal_ParticlesTwo: 0},
	{SqureGreen: 0},
	{ActDied: 0},
	{ActTouchGun: 0},
	{AnimName: 0},
	{Enemy: 0},
	{Физика: 0},
	{Blood_Square: 0},
	{Emeny_Floor: 0},
	{Emeny_UID: 0},
	{ActMove: 0},
	{RndJump: 0},
	{Size: 0},
	{BossMoving: 0},
	{ActGost: 0},
	{EmenyPdl: 0},
	{BossMovingAct: 0},
	{Table_Heart: 0},
	{Table_One: 0},
	{Table_Pause: 0},
	{Table_Win: 0},
	{NameTableWIn: 0},
	{Table_Lose: 0},
	{NameTableLose: 0},
	{Table_OneInvet: 0},
	{Table_HeroChange: 0},
	{Table_HeroGunChange: 0},
	{Text_EmenyDied: 0},
	{Text_Coins: 0},
	{Text_Heart: 0},
	{Text_Pause: 0},
	{Text_Continue: 0},
	{Next_Continue: 0},
	{Text_Inventory: 0},
	{Text_NameLose: 0},
	{Text_Skip: 0},
	{Text_Again: 0},
	{Text_NameWin: 0},
	{Text_Reward: 0},
	{Text_FigthHome: 0},
	{Text_BuyHero: 0},
	{Text_Buy: 0},
	{Text_GunNextUpgrade: 0},
	{Text_Help: 0},
	{Text_EdiControl: 0},
	{Text_EdMoving: 0},
	{Scull: 0},
	{Heart: 0},
	{Coin: 0},
	{Clouds: 0},
	{Scull_Dead: 0},
	{Hero_Shadow: 0},
	{Upgrade: 0},
	{GunChange_Home: 0},
	{Lock: 0},
	{Svet: 0},
	{QuestionMark: 0},
	{QuestionMarkPDL: 0},
	{Btn_Edication: 0},
	{BtnEdcGunOne: 0},
	{ArrowEd_Btn: 0},
	{Ed_Mouse: 0},
	{Line: 0},
	{LoudTwo: 0},
	{Синусоид: 0},
	{Louder_Icon: 0},
	{Btn_Soc: 0},
	{Btn_VK: 0},
	{Platforms_Famaly: 0},
	{Btn_Top: 0},
	{Gun_Famaly: 0},
	{Enemies_Famaly: 0},
	{EmenyPDL_Famaly: 0},
	{Btn_Big: 0},
	{Btn_LeftHome: 0},
	{TouchLeftID: 0},
	{TouchRightID: 0},
	{TouchUPRightID: 0},
	{speed: 0},
	{StrongGun: 0},
	{EmenyUID: 0},
	{GunID: 0},
	{GunNow: 0},
	{GunNowBulet: 0},
	{RndSqureYellowe: 0},
	{Coins: 0},
	{levt: 0},
	{Level: 0},
	{Education: 0},
	{Priz: 0},
	{PrizTwo: 0},
	{PrizHome: 0},
	{PrizHomeTwo: 0},
	{ReklSound: 0},
	{Vkladla: 0},
	{Focus: 0},
	{ActWin: 0},
	{ActReclama: 0},
	{ActJostyc: 0},
	{ActFigthGun: 0},
	{PeakPizda: 0},
	{ActTochGun: 0},
	{ActThorAnim: 0},
	{ActGunRotate: 0},
	{GunsExists: 0},
	{GunSwordAngel: 0},
	{GunView: 0},
	{GunHeroNow: 0},
	{GunOneTwo: 0},
	{GunOneThree: 0},
	{GunVikingTwo: 0},
	{GunVikingThree: 0},
	{GunSoldierTwo: 0},
	{GunSoldierThree: 0},
	{GunPirateTwo: 0},
	{GunPirateThree: 0},
	{GunGladiatorTwo: 0},
	{GunGladiatorThree: 0},
	{PeakShoting: 0},
	{BloodCurrX: 0},
	{DiedEmeny_Need: 0},
	{DiedEmeny_Now: 0},
	{TimeHoldRnd: 0},
	{ActHeroJump: 0},
	{ActHeroDied: 0},
	{ActWorkGun: 0},
	{HeroJumpVal: 0},
	{HeroHeart: 0},
	{HeroFace: 0},
	{HeroFaceTable: 0},
	{HeroFaceName: 0},
	{FaceViking: 0},
	{FaceSoldier: 0},
	{FacePirate: 0},
	{FaceGladiator: 0},
	{HeroFacePrice: 0},
	{SoundAct: 0},
	{ActBtn_Block: 0},
	{ActBtn_Two: 0},
	{ActCloud: 0},
	{TochOneAng: 0},
	{TochOneDest: 0},
	{TochOneVarX: 0},
	{TochOneVarY: 0},
	{TochTwoAng: 0},
	{TochTwoDest: 0},
	{TochTwoVarX: 0},
	{TochTwoVarY: 0},
	{Lang_Ynd: 0},
	{lang: 0},
	{screen: 0},
	{itm: 0},
	{HeroFaceNow: 0},
	{ID_btn: 0},
	{Act_Toch: 0},
	{SpringLog: 0},
	{Louder: 0}
];

self.InstanceType = {
	Hero: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	HeroHome: class extends self.ISpriteInstance {},
	HeroDead: class extends self.ISpriteInstance {},
	Bagr: class extends self.ISpriteInstance {},
	Bagr_Win: class extends self.ISpriteInstance {},
	Bagr_WinSetting: class extends self.ISpriteInstance {},
	Bagr_Inventary: class extends self.ISpriteInstance {},
	Bagr_Help: class extends self.ISpriteInstance {},
	BagrTop: class extends self.ISpriteInstance {},
	BagrBottom: class extends self.ISpriteInstance {},
	Sky_Nigth: class extends self.ISpriteInstance {},
	SkyDark: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Platform_One: class extends self.ISpriteInstance {},
	Platform_Two: class extends self.ISpriteInstance {},
	Grass: class extends self.ISpriteInstance {},
	Platform_TwoBlack: class extends self.ISpriteInstance {},
	PlatformDop: class extends self.ISpriteInstance {},
	BlackBlock_bagr: class extends self.ISpriteInstance {},
	BlockOneBok: class extends self.ISpriteInstance {},
	BlockOneTitle: class extends self.ITiledBackgroundInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Palka: class extends self.ISpriteInstance {},
	Saw: class extends self.ISpriteInstance {},
	BlockPdl: class extends self.ISpriteInstance {},
	PlatformaScvoz: class extends self.ISpriteInstance {},
	Platform_ThreeBlack: class extends self.ISpriteInstance {},
	BlockIron: class extends self.ISpriteInstance {},
	BlockFall: class extends self.ISpriteInstance {},
	Ocean: class extends self.ISpriteInstance {},
	OceanPDL: class extends self.ISpriteInstance {},
	OceanMount: class extends self.ISpriteInstance {},
	OceanSin: class extends self.ISpriteInstance {},
	BrickWall: class extends self.ISpriteInstance {},
	BrickWallTitles: class extends self.ITiledBackgroundInstance {},
	BrickWallTwo: class extends self.ISpriteInstance {},
	Blocks_stoun: class extends self.ITiledBackgroundInstance {},
	Spring: class extends self.ISpriteInstance {},
	Blocks_sandDark: class extends self.ITiledBackgroundInstance {},
	Block_Lava: class extends self.ITiledBackgroundInstance {},
	LavaCollision: class extends self.ISpriteInstance {},
	PeakLift: class extends self.ISpriteInstance {},
	PeakLiftPdl: class extends self.ISpriteInstance {},
	Btn_Sound: class extends self.ISpriteInstance {},
	Btn_Pause: class extends self.ISpriteInstance {},
	Btn_PauseСontinue: class extends self.ISpriteInstance {},
	Btn_Next: class extends self.ISpriteInstance {},
	Btn_Inventory: class extends self.ISpriteInstance {},
	Btn_Skip: class extends self.ISpriteInstance {},
	Btn_Again: class extends self.ISpriteInstance {},
	Btn_GunChange: class extends self.ISpriteInstance {},
	Btn_Figth: class extends self.ISpriteInstance {},
	Btn_FaceHero: class extends self.ISpriteInstance {},
	Btn_HeroGun: class extends self.ISpriteInstance {},
	Btn_Reward: class extends self.ISpriteInstance {},
	Btn_StartGame: class extends self.ISpriteInstance {},
	Btn_Crestic: class extends self.ISpriteInstance {},
	Btn_Arrow: class extends self.ISpriteInstance {},
	Btn_Buy: class extends self.ISpriteInstance {},
	BtnBottom_Pdl: class extends self.ISpriteInstance {},
	Vbtn_up: class extends self.ISpriteInstance {},
	BtnMob_Left: class extends self.ISpriteInstance {},
	BtnMob_Rigth: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	LocalHost: class extends self.IInstance {},
	device: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sword: class extends self.ISpriteInstance {},
	Gun_Btn: class extends self.ISpriteInstance {},
	Onion: class extends self.ISpriteInstance {},
	Peaks: class extends self.ISpriteInstance {},
	Onion_Arrow: class extends self.ISpriteInstance {},
	PeakPdl: class extends self.ISpriteInstance {},
	ArrowPdl: class extends self.ISpriteInstance {},
	Bulova: class extends self.ISpriteInstance {},
	Thor: class extends self.ISpriteInstance {},
	AxeV: class extends self.ISpriteInstance {},
	AxePdl: class extends self.ISpriteInstance {},
	Guns: class extends self.ISpriteInstance {},
	Flame_Gun: class extends self.ISpriteInstance {},
	Bulet: class extends self.ISpriteInstance {},
	Raketa: class extends self.ISpriteInstance {},
	PrtclSmook: class extends self.IParticlesInstance {},
	Smook: class extends self.ISpriteInstance {},
	BoomRak: class extends self.ISpriteInstance {},
	SwordPirate: class extends self.ISpriteInstance {},
	BuletPirate: class extends self.ISpriteInstance {},
	BoomZombi: class extends self.ISpriteInstance {},
	Spear: class extends self.ISpriteInstance {},
	SpearPDL: class extends self.ISpriteInstance {},
	AxeG: class extends self.ISpriteInstance {},
	Throm: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	SqureYellowe: class extends self.ISpriteInstance {},
	Portal_Particles: class extends self.ISpriteInstance {},
	Portal_ParticlesTwo: class extends self.ISpriteInstance {},
	SqureGreen: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Blood_Square: class extends self.ISpriteInstance {},
	Emeny_Floor: class extends self.ISpriteInstance {},
	EmenyPdl: class extends self.ISpriteInstance {},
	BossMovingAct: class extends self.ISpriteInstance {},
	Table_Heart: class extends self.ISpriteInstance {},
	Table_One: class extends self.ISpriteInstance {},
	Table_Pause: class extends self.ISpriteInstance {},
	Table_Win: class extends self.ISpriteInstance {},
	NameTableWIn: class extends self.ISpriteInstance {},
	Table_Lose: class extends self.ISpriteInstance {},
	NameTableLose: class extends self.ISpriteInstance {},
	Table_OneInvet: class extends self.ISpriteInstance {},
	Table_HeroChange: class extends self.ISpriteInstance {},
	Table_HeroGunChange: class extends self.ISpriteInstance {},
	Text_EmenyDied: class extends self.ITextInstance {},
	Text_Coins: class extends self.ITextInstance {},
	Text_Heart: class extends self.ITextInstance {},
	Text_Pause: class extends self.ITextInstance {},
	Text_Continue: class extends self.ITextInstance {},
	Next_Continue: class extends self.ITextInstance {},
	Text_Inventory: class extends self.ITextInstance {},
	Text_NameLose: class extends self.ITextInstance {},
	Text_Skip: class extends self.ITextInstance {},
	Text_Again: class extends self.ITextInstance {},
	Text_NameWin: class extends self.ITextInstance {},
	Text_Reward: class extends self.ITextInstance {},
	Text_FigthHome: class extends self.ITextInstance {},
	Text_BuyHero: class extends self.ITextInstance {},
	Text_Buy: class extends self.ITextInstance {},
	Text_GunNextUpgrade: class extends self.ITextInstance {},
	Text_Help: class extends self.ITextInstance {},
	Text_EdiControl: class extends self.ITextInstance {},
	Text_EdMoving: class extends self.ITextInstance {},
	Scull: class extends self.ISpriteInstance {},
	Heart: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Clouds: class extends self.ISpriteInstance {},
	Scull_Dead: class extends self.ISpriteInstance {},
	Hero_Shadow: class extends self.ISpriteInstance {},
	GunChange_Home: class extends self.ISpriteInstance {},
	Lock: class extends self.ISpriteInstance {},
	Svet: class extends self.ISpriteInstance {},
	QuestionMark: class extends self.ISpriteInstance {},
	QuestionMarkPDL: class extends self.ISpriteInstance {},
	Btn_Edication: class extends self.ISpriteInstance {},
	BtnEdcGunOne: class extends self.ISpriteInstance {},
	ArrowEd_Btn: class extends self.ISpriteInstance {},
	Ed_Mouse: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	LoudTwo: class extends self.ISpriteInstance {},
	Louder_Icon: class extends self.ISpriteInstance {},
	Btn_Soc: class extends self.ISpriteInstance {},
	Btn_VK: class extends self.ISpriteInstance {},
	Platforms_Famaly: class extends self.ISpriteInstance {},
	Btn_Top: class extends self.ISpriteInstance {},
	Gun_Famaly: class extends self.ISpriteInstance {},
	Enemies_Famaly: class extends self.ISpriteInstance {},
	EmenyPDL_Famaly: class extends self.ISpriteInstance {},
	Btn_Big: class extends self.ISpriteInstance {},
	Btn_LeftHome: class extends self.ISpriteInstance {}
}