const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.EightDir,
		C3.Behaviors.LOS,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Particles,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.Action_Event1_Act1,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Audio.Acts.PreloadByName,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.ScriptsInEvents.Action_Event7_Act7,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Pathfinding.Exps.NodeXAt,
		C3.Behaviors.Pathfinding.Exps.CurrentNode,
		C3.Behaviors.Pathfinding.Exps.NodeYAt,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Particles.Acts.SetSizeRandomiser,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Particles.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.ScriptsInEvents.Action_Event1480_Act2,
		C3.Plugins.System.Acts.SetTimescale,
		C3.ScriptsInEvents.Action_Event1483_Act2,
		C3.ScriptsInEvents.Action_Event1487_Act2,
		C3.ScriptsInEvents.Action_Event1491_Act2,
		C3.ScriptsInEvents.Action_Event1495_Act2,
		C3.ScriptsInEvents.Action_Event1499_Act2,
		C3.ScriptsInEvents.Action_Event1503_Act2,
		C3.ScriptsInEvents.Action_Event1507_Act2,
		C3.ScriptsInEvents.Action_Event1511_Act2,
		C3.ScriptsInEvents.Action_Event1515_Act2,
		C3.ScriptsInEvents.Action_Event1519_Act2,
		C3.ScriptsInEvents.Action_Event1523_Act2,
		C3.ScriptsInEvents.Action_Event1527_Act3,
		C3.ScriptsInEvents.Action_Event1556_Act1,
		C3.ScriptsInEvents.Action_Event1558_Act1,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.ScriptsInEvents.Btns_Event89_Act2,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.ScriptsInEvents.Menu_Event112_Act3,
		C3.ScriptsInEvents.Menu_Event113_Act3,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex
	];
};
self.C3_JsPropNameTable = [
	{Hero_Body: 0},
	{Мигание: 0},
	{Hero_Hand: 0},
	{Circle_Faier: 0},
	{Hero_BodyMenu: 0},
	{Hero_HandMenu: 0},
	{Bronic: 0},
	{Caska: 0},
	{Bagr: 0},
	{Grass: 0},
	{Твинанимация: 0},
	{Bagr_Win: 0},
	{Bagr_WinSetting: 0},
	{Bagr_Menu: 0},
	{Bagr_MenuGun: 0},
	{Brush: 0},
	{Brush_01: 0},
	{Brush_02: 0},
	{Bagr_Black: 0},
	{Bagr_Shadow: 0},
	{Wall: 0},
	{WallTwo: 0},
	{Life: 0},
	{"8Направлений": 0},
	{ПолеЗрения: 0},
	{Collision_Player: 0},
	{Твёрдый: 0},
	{Collision_Wall: 0},
	{ActMove: 0},
	{ID: 0},
	{ZombeUID: 0},
	{Act: 0},
	{DamagePlaeyr: 0},
	{Collision_Zombe: 0},
	{Touch: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Sound: 0},
	{LocalHost: 0},
	{device: 0},
	{Particles_Smoke: 0},
	{Smouk: 0},
	{Zombe: 0},
	{PointBornZombe: 0},
	{ZombiVis: 0},
	{Recoil: 0},
	{ПоискПути: 0},
	{Gun: 0},
	{Plr: 0},
	{Strong: 0},
	{Пуля: 0},
	{Bulet: 0},
	{Прикрепить: 0},
	{Flame_Gun: 0},
	{trace: 0},
	{BoomZombi: 0},
	{BulletGrant: 0},
	{BN: 0},
	{FlameRaketa: 0},
	{PrtclSmook: 0},
	{Raketa: 0},
	{Btn_Pause: 0},
	{Name: 0},
	{Btn_Setting: 0},
	{Btn_Crestic: 0},
	{Btn_Restart: 0},
	{Trig: 0},
	{name: 0},
	{Btn_Next: 0},
	{BtnPause: 0},
	{Btn_Home: 0},
	{Btn_Again: 0},
	{Btn_Fith: 0},
	{BtnColorsMenu: 0},
	{BtnSkinsMenu: 0},
	{BtnCresticMenu: 0},
	{Bid: 0},
	{NameIcon: 0},
	{IconStoim: 0},
	{BtnGunsMenu: 0},
	{Btn_Soc: 0},
	{Btn_VK: 0},
	{Joy: 0},
	{Stick: 0},
	{Line: 0},
	{Line_Bagr: 0},
	{Pid: 0},
	{Progress: 0},
	{Playueruid: 0},
	{Progress_Line: 0},
	{HandZomby: 0},
	{Header_Setting: 0},
	{Table_Setting: 0},
	{TableNameSkill: 0},
	{Text_HeaderSetting: 0},
	{Text_Music: 0},
	{Text_Sound: 0},
	{Text_Pause: 0},
	{Text_Resume: 0},
	{Text_NameSkill: 0},
	{Text_SkillDescription: 0},
	{Text_SkillProgress: 0},
	{Text_UnlockGun: 0},
	{Text_PushMe: 0},
	{Text_NewWaves: 0},
	{Text_Lose: 0},
	{Text_HomeBtn: 0},
	{Text_BtnAgain: 0},
	{Text_BtnFigth: 0},
	{Waves: 0},
	{Text_SaleGun: 0},
	{CardSkill: 0},
	{CardGun: 0},
	{CardMenuGun: 0},
	{CardBronic: 0},
	{Shadow: 0},
	{СледитьЗа: 0},
	{Camera: 0},
	{ShadowMenu: 0},
	{Smook: 0},
	{ArrayRnd: 0},
	{Bagr_Two: 0},
	{Поворот: 0},
	{LoudTwo: 0},
	{Синусоид: 0},
	{Louder_Icon: 0},
	{Физика: 0},
	{Таймер: 0},
	{Zombi_Famaly: 0},
	{Btn_Top: 0},
	{Card_Famaly: 0},
	{Btn_Lose: 0},
	{Btn_Menu: 0},
	{speed: 0},
	{LERP_SMOOTHNESS: 0},
	{RndPointBornZomby: 0},
	{Lang_Ynd: 0},
	{lang: 0},
	{screen: 0},
	{itm: 0},
	{ActMovingZombie: 0},
	{Focus: 0},
	{ActJostyc: 0},
	{ActReclama: 0},
	{ActTimer: 0},
	{BtnBlock: 0},
	{DeadHero: 0},
	{ActBtnAll: 0},
	{CresticAct: 0},
	{SoundAct: 0},
	{MusicAct: 0},
	{asda: 0},
	{TimeShoot: 0},
	{StrongBulet: 0},
	{SpeedZombi: 0},
	{TimeBornZombe: 0},
	{DellZomby: 0},
	{DellZombyNow: 0},
	{Line_With: 0},
	{Line_WithStep: 0},
	{Wave: 0},
	{Music: 0},
	{Priz: 0},
	{PrizTwo: 0},
	{ReklSound: 0},
	{RndBornZomby: 0},
	{Kaska: 0},
	{GunUnlock: 0},
	{LifeHero: 0},
	{LifeHeroUpdate: 0},
	{LifeZombiUpdate: 0},
	{GunChoose: 0},
	{GunChooseBronic: 0},
	{GunChooseKaska: 0},
	{GunStrongPlusOne: 0},
	{GunSpeedPlusOne: 0},
	{GunStrongPlusTwo: 0},
	{GunSpeedPlusTwo: 0},
	{GunStrongPlusThree: 0},
	{GunSpeedPlusThree: 0},
	{GunStrongPlusFore: 0},
	{GunSpeedPlusFore: 0},
	{GunStrongPlusFive: 0},
	{GunSpeedPlusFive: 0},
	{GunStrongPlusSixe: 0},
	{GunSpeedPlusSixe: 0},
	{GunStrongPlusSeven: 0},
	{GunSpeedPlusSeven: 0},
	{GunStrongPlusEigth: 0},
	{GunSpeedPlusEigth: 0},
	{SoundGun: 0},
	{Vkladla: 0},
	{ProgressLinePlayer: 0},
	{Louder: 0},
	{Abd: 0}
];

self.InstanceType = {
	Hero_Body: class extends self.ISpriteInstance {},
	Hero_Hand: class extends self.ISpriteInstance {},
	Circle_Faier: class extends self.ISpriteInstance {},
	Hero_BodyMenu: class extends self.ISpriteInstance {},
	Hero_HandMenu: class extends self.ISpriteInstance {},
	Bronic: class extends self.ISpriteInstance {},
	Caska: class extends self.ISpriteInstance {},
	Bagr: class extends self.ISpriteInstance {},
	Grass: class extends self.ISpriteInstance {},
	Bagr_Win: class extends self.ISpriteInstance {},
	Bagr_WinSetting: class extends self.ISpriteInstance {},
	Bagr_Menu: class extends self.ISpriteInstance {},
	Bagr_MenuGun: class extends self.ISpriteInstance {},
	Brush: class extends self.ISpriteInstance {},
	Brush_01: class extends self.ISpriteInstance {},
	Brush_02: class extends self.ISpriteInstance {},
	Bagr_Black: class extends self.ISpriteInstance {},
	Bagr_Shadow: class extends self.ITiledBackgroundInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	WallTwo: class extends self.ITiledBackgroundInstance {},
	Collision_Player: class extends self.ISpriteInstance {},
	Collision_Wall: class extends self.ISpriteInstance {},
	Collision_Zombe: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	LocalHost: class extends self.IInstance {},
	device: class extends self.IInstance {},
	Particles_Smoke: class extends self.IParticlesInstance {},
	Smouk: class extends self.ISpriteInstance {},
	Zombe: class extends self.ISpriteInstance {},
	PointBornZombe: class extends self.ISpriteInstance {},
	Gun: class extends self.ISpriteInstance {},
	Bulet: class extends self.ISpriteInstance {},
	Flame_Gun: class extends self.ISpriteInstance {},
	trace: class extends self.ISpriteInstance {},
	BoomZombi: class extends self.ISpriteInstance {},
	BulletGrant: class extends self.ISpriteInstance {},
	BN: class extends self.ISpriteInstance {},
	FlameRaketa: class extends self.ISpriteInstance {},
	PrtclSmook: class extends self.IParticlesInstance {},
	Raketa: class extends self.ISpriteInstance {},
	Btn_Pause: class extends self.ISpriteInstance {},
	Btn_Setting: class extends self.ISpriteInstance {},
	Btn_Crestic: class extends self.ISpriteInstance {},
	Btn_Restart: class extends self.ISpriteInstance {},
	Trig: class extends self.ISpriteInstance {},
	Btn_Next: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	Btn_Home: class extends self.ISpriteInstance {},
	Btn_Again: class extends self.ISpriteInstance {},
	Btn_Fith: class extends self.ISpriteInstance {},
	BtnColorsMenu: class extends self.ISpriteInstance {},
	BtnSkinsMenu: class extends self.ISpriteInstance {},
	BtnCresticMenu: class extends self.ISpriteInstance {},
	IconStoim: class extends self.ISpriteInstance {},
	BtnGunsMenu: class extends self.ISpriteInstance {},
	Btn_Soc: class extends self.ISpriteInstance {},
	Btn_VK: class extends self.ISpriteInstance {},
	Joy: class extends self.ISpriteInstance {},
	Stick: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Line_Bagr: class extends self.ISpriteInstance {},
	Progress: class extends self.ISpriteInstance {},
	Progress_Line: class extends self.ISpriteInstance {},
	HandZomby: class extends self.ISpriteInstance {},
	Header_Setting: class extends self.ISpriteInstance {},
	Table_Setting: class extends self.ISpriteInstance {},
	TableNameSkill: class extends self.ISpriteInstance {},
	Text_HeaderSetting: class extends self.ITextInstance {},
	Text_Music: class extends self.ITextInstance {},
	Text_Sound: class extends self.ITextInstance {},
	Text_Pause: class extends self.ITextInstance {},
	Text_Resume: class extends self.ITextInstance {},
	Text_NameSkill: class extends self.ITextInstance {},
	Text_SkillDescription: class extends self.ITextInstance {},
	Text_SkillProgress: class extends self.ITextInstance {},
	Text_UnlockGun: class extends self.ITextInstance {},
	Text_PushMe: class extends self.ITextInstance {},
	Text_NewWaves: class extends self.ITextInstance {},
	Text_Lose: class extends self.ITextInstance {},
	Text_HomeBtn: class extends self.ITextInstance {},
	Text_BtnAgain: class extends self.ITextInstance {},
	Text_BtnFigth: class extends self.ITextInstance {},
	Text_SaleGun: class extends self.ITextInstance {},
	CardSkill: class extends self.ISpriteInstance {},
	CardGun: class extends self.ISpriteInstance {},
	CardMenuGun: class extends self.ISpriteInstance {},
	CardBronic: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	ShadowMenu: class extends self.ISpriteInstance {},
	Smook: class extends self.ISpriteInstance {},
	ArrayRnd: class extends self.IArrayInstance {},
	Bagr_Two: class extends self.ISpriteInstance {},
	LoudTwo: class extends self.ISpriteInstance {},
	Louder_Icon: class extends self.ISpriteInstance {},
	Zombi_Famaly: class extends self.ISpriteInstance {},
	Btn_Top: class extends self.ISpriteInstance {},
	Card_Famaly: class extends self.ISpriteInstance {},
	Btn_Lose: class extends self.ISpriteInstance {},
	Btn_Menu: class extends self.ISpriteInstance {}
}