const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.Action_Event1_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.JavaScriptInEvents.Action_Event92_Act1,
		C3.Plugins.System.Acts.AddVar,
		C3.JavaScriptInEvents.Action_Event96_Act1,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.JavaScriptInEvents.Action_Event122_Act1,
		C3.JavaScriptInEvents.Action_Event134_Act1,
		C3.JavaScriptInEvents.Action_Event157_Act1,
		C3.JavaScriptInEvents.Action_Event209_Act3,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.JavaScriptInEvents.Buttons_Event41_Act1,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Start_Event24_Act3,
		C3.JavaScriptInEvents.Start_Event25_Act3
	];
};
self.C3_JsPropNameTable = [
	{Bagr: 0},
	{Bagr_Field: 0},
	{Bagr_FieldMask: 0},
	{Bagr_FieldTwo: 0},
	{Ramka: 0},
	{Bagr_PsLWin: 0},
	{Bagr_Help: 0},
	{Bagr_Two: 0},
	{Твинанимация: 0},
	{Bagr_Win: 0},
	{Pdl_UiTop: 0},
	{Browser: 0},
	{Sound: 0},
	{LocalHost: 0},
	{Touch: 0},
	{Act: 0},
	{Row: 0},
	{Line: 0},
	{Var: 0},
	{NumPoint: 0},
	{curY: 0},
	{ActToch: 0},
	{ActLine: 0},
	{ActRow: 0},
	{curX: 0},
	{ActDel: 0},
	{ActFind: 0},
	{ActDown: 0},
	{NumDown: 0},
	{ActCrestic: 0},
	{Blocks: 0},
	{BlockDemo: 0},
	{Btn_Settings: 0},
	{Btn_Bomba: 0},
	{Btn_Crestik: 0},
	{Btn_Multy: 0},
	{Btn_Reward: 0},
	{Bagr_Line: 0},
	{Green_Line: 0},
	{Name: 0},
	{Btn_Crestic: 0},
	{Btn_Restrt: 0},
	{Btn_Sound: 0},
	{ID: 0},
	{Btn_Priz: 0},
	{Btn_Start: 0},
	{Btn_Again: 0},
	{Bit: 0},
	{NameIcon: 0},
	{Table_Sale: 0},
	{Table_Dimand: 0},
	{TableBagr_Setting: 0},
	{Header_Setting: 0},
	{Table_Score: 0},
	{Text_Bid: 0},
	{Text_Dimand: 0},
	{Text_ScoreHere: 0},
	{Text_HeaderSetting: 0},
	{Text_Score: 0},
	{Text_BestScore: 0},
	{Text_Help: 0},
	{Text_ScoreFirst: 0},
	{Text_PricePriz: 0},
	{Text_Priz: 0},
	{Text_RewardProgress: 0},
	{Text_NextLevel: 0},
	{Text_BlockDell: 0},
	{Text_StartMenu: 0},
	{Text_Again: 0},
	{ArrayNum: 0},
	{Joy: 0},
	{Stick: 0},
	{SliderToch: 0},
	{Diamonds: 0},
	{Cup: 0},
	{Сrown: 0},
	{DontToch: 0},
	{Tween: 0},
	{ticker: 0},
	{Finger: 0},
	{TochDont: 0},
	{Поворот: 0},
	{LoudTwo: 0},
	{Синусоид: 0},
	{Louder_Icon: 0},
	{NameGame: 0},
	{Btn_Soc: 0},
	{Btn_VK: 0},
	{BtnSett: 0},
	{BtnBott: 0},
	{Btn_StartMenu: 0},
	{LERP_SMOOTHNESS: 0},
	{VarBlock: 0},
	{Moving: 0},
	{Priz: 0},
	{PrizTwo: 0},
	{ReklSound: 0},
	{Education: 0},
	{Vkladla: 0},
	{RndStart: 0},
	{RndEnd: 0},
	{RndVar: 0},
	{RndVarBigCell: 0},
	{RndVarBlockLvl: 0},
	{Score: 0},
	{ScorePlus: 0},
	{ScoreHere: 0},
	{RecordScore: 0},
	{numCombo: 0},
	{Ticker_Num: 0},
	{Level: 0},
	{LineBlocks: 0},
	{RowBlocks: 0},
	{CurX: 0},
	{CurY: 0},
	{BeBlocks: 0},
	{RowEffect: 0},
	{LineEffect: 0},
	{NumVar: 0},
	{NumVarBlock: 0},
	{Line_With: 0},
	{Line_WithStep: 0},
	{Vkladla2: 0},
	{ActTochStick: 0},
	{ActJosticLetgo: 0},
	{ActLeTwo: 0},
	{ActLesdfasfd: 0},
	{ActSLideTrue: 0},
	{ActFindNum: 0},
	{ActTochBtn: 0},
	{ActTochBtnSetting: 0},
	{ActTochCrestic: 0},
	{SoundAct: 0},
	{ActTochMylti: 0},
	{ActTochBomb: 0},
	{ActTochBombTwo: 0},
	{ActTochCreticEff: 0},
	{ActTochCreticEffDown: 0},
	{ActLevelFet: 0},
	{Focus: 0},
	{ActReclama: 0},
	{Lang_Ynd: 0},
	{lang: 0},
	{screen: 0},
	{itm: 0},
	{Louder: 0}
];

self.InstanceType = {
	Bagr: class extends self.ISpriteInstance {},
	Bagr_Field: class extends self.ISpriteInstance {},
	Bagr_FieldMask: class extends self.ISpriteInstance {},
	Bagr_FieldTwo: class extends self.ISpriteInstance {},
	Ramka: class extends self.ISpriteInstance {},
	Bagr_PsLWin: class extends self.ISpriteInstance {},
	Bagr_Help: class extends self.ISpriteInstance {},
	Bagr_Two: class extends self.ISpriteInstance {},
	Bagr_Win: class extends self.ISpriteInstance {},
	Pdl_UiTop: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	LocalHost: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	NumPoint: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	BlockDemo: class extends self.ISpriteInstance {},
	Btn_Settings: class extends self.ISpriteInstance {},
	Btn_Bomba: class extends self.ISpriteInstance {},
	Btn_Crestik: class extends self.ISpriteInstance {},
	Btn_Multy: class extends self.ISpriteInstance {},
	Btn_Reward: class extends self.ISpriteInstance {},
	Bagr_Line: class extends self.ISpriteInstance {},
	Green_Line: class extends self.ISpriteInstance {},
	Btn_Crestic: class extends self.ISpriteInstance {},
	Btn_Restrt: class extends self.ISpriteInstance {},
	Btn_Sound: class extends self.ISpriteInstance {},
	Btn_Priz: class extends self.ISpriteInstance {},
	Btn_Start: class extends self.ISpriteInstance {},
	Btn_Again: class extends self.ISpriteInstance {},
	Table_Sale: class extends self.ISpriteInstance {},
	Table_Dimand: class extends self.ISpriteInstance {},
	TableBagr_Setting: class extends self.ISpriteInstance {},
	Header_Setting: class extends self.ISpriteInstance {},
	Table_Score: class extends self.ISpriteInstance {},
	Text_Bid: class extends self.ITextInstance {},
	Text_Dimand: class extends self.ITextInstance {},
	Text_ScoreHere: class extends self.ITextInstance {},
	Text_HeaderSetting: class extends self.ITextInstance {},
	Text_Score: class extends self.ITextInstance {},
	Text_BestScore: class extends self.ITextInstance {},
	Text_Help: class extends self.ITextInstance {},
	Text_ScoreFirst: class extends self.ITextInstance {},
	Text_PricePriz: class extends self.ITextInstance {},
	Text_Priz: class extends self.ITextInstance {},
	Text_RewardProgress: class extends self.ITextInstance {},
	Text_NextLevel: class extends self.ITextInstance {},
	Text_BlockDell: class extends self.ITextInstance {},
	Text_StartMenu: class extends self.ITextInstance {},
	Text_Again: class extends self.ITextInstance {},
	ArrayNum: class extends self.IArrayInstance {},
	Joy: class extends self.ISpriteInstance {},
	Stick: class extends self.ISpriteInstance {},
	SliderToch: class extends self.ISpriteInstance {},
	Diamonds: class extends self.ISpriteInstance {},
	Cup: class extends self.ISpriteInstance {},
	Сrown: class extends self.ISpriteInstance {},
	DontToch: class extends self.ISpriteInstance {},
	ticker: class extends self.ISpriteInstance {},
	Finger: class extends self.ISpriteInstance {},
	TochDont: class extends self.ISpriteInstance {},
	LoudTwo: class extends self.ISpriteInstance {},
	Louder_Icon: class extends self.ISpriteInstance {},
	NameGame: class extends self.ISpriteInstance {},
	Btn_Soc: class extends self.ISpriteInstance {},
	Btn_VK: class extends self.ISpriteInstance {},
	BtnSett: class extends self.ISpriteInstance {},
	BtnBott: class extends self.ISpriteInstance {},
	Btn_StartMenu: class extends self.ISpriteInstance {}
}