const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.Action_Event1_Act1,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.ScriptsInEvents.Action_Event19_Act2,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.ScriptsInEvents.Action_Event97_Act2,
		C3.ScriptsInEvents.Action_Event101_Act2,
		C3.ScriptsInEvents.Action_Event106_Act1,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.ScriptsInEvents.Action_Event205_Act1,
		C3.Plugins.System.Cnds.Compare,
		C3.ScriptsInEvents.Action_Event207_Act2,
		C3.ScriptsInEvents.Action_Event210_Act1,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.ScriptsInEvents.Buttons_Event45_Act2,
		C3.ScriptsInEvents.Buttons_Event51_Act4,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.ScriptsInEvents.Start_Event1_Act6,
		C3.ScriptsInEvents.Start_Event15_Act3,
		C3.ScriptsInEvents.Start_Event16_Act3
	];
};
self.C3_JsPropNameTable = [
	{Bagr_Small: 0},
	{BagrMenuDown: 0},
	{Bagr_Two: 0},
	{Твинанимация: 0},
	{Bagr_Win: 0},
	{Bagr_Help: 0},
	{Bagr_PauseLose: 0},
	{Browser: 0},
	{Sound: 0},
	{LocalHost: 0},
	{Touch: 0},
	{Act: 0},
	{Row: 0},
	{Line: 0},
	{Var: 0},
	{Cell_Bagr: 0},
	{BagrChoiseCell: 0},
	{ID: 0},
	{ActToch: 0},
	{CorX: 0},
	{CorY: 0},
	{ActFind: 0},
	{ActFirst: 0},
	{VarCadr: 0},
	{Физика: 0},
	{Cells: 0},
	{Cell_Pdl: 0},
	{CellsSmall: 0},
	{Cell_Point: 0},
	{CellPDL: 0},
	{Cell_Multy: 0},
	{Ver: 0},
	{CellsProgress: 0},
	{Btn_Pause: 0},
	{Btn_Reward: 0},
	{Btn_Hummer: 0},
	{Btn_Cancel: 0},
	{Btn_Multy: 0},
	{Btn_Sound: 0},
	{Btn_Restart: 0},
	{Btn_Crestic: 0},
	{Btn_Priz: 0},
	{Btn_Start: 0},
	{Table_Score: 0},
	{Table_Diamonds: 0},
	{Bit: 0},
	{NameIcon: 0},
	{Table_Sale: 0},
	{Table_Pause: 0},
	{Table_ReclamaPause: 0},
	{Text_Score: 0},
	{Text_Best: 0},
	{Text_Diamonds: 0},
	{Text_Sale: 0},
	{Text_Help: 0},
	{Text_PauseLose: 0},
	{Text_Sound: 0},
	{Text_Restart: 0},
	{Text_PricePriz: 0},
	{Text_Priz: 0},
	{Text_ProgressOne: 0},
	{Text_ProgressTwo: 0},
	{Text_ComBreak: 0},
	{Text_ComBreakRead: 0},
	{Collider_Hummer: 0},
	{PDL_Toch: 0},
	{Pdl_UIup: 0},
	{MyltiPDL: 0},
	{ArrayCells: 0},
	{Сrown: 0},
	{Cup: 0},
	{Diamonds: 0},
	{Hummer: 0},
	{Поворот: 0},
	{LoudTwo: 0},
	{Синусоид: 0},
	{Louder_Icon: 0},
	{NameGame: 0},
	{Finger: 0},
	{Btn_Soc: 0},
	{Btn_VK: 0},
	{BtnEffects: 0},
	{Btn_Big: 0},
	{Priz: 0},
	{PrizTwo: 0},
	{ReklSound: 0},
	{RndStart: 0},
	{RndEnd: 0},
	{RndVar: 0},
	{RndVarBigCell: 0},
	{Score: 0},
	{RecordScore: 0},
	{numCombo: 0},
	{NumVar: 0},
	{NumVarEmpty: 0},
	{Cur_X: 0},
	{Cur_Y: 0},
	{ProgressOne: 0},
	{ProgressTwo: 0},
	{ProgressCelD: 0},
	{Education: 0},
	{Vkladla: 0},
	{ActTimer: 0},
	{BtnBlock: 0},
	{ActTochBlock: 0},
	{ActTochHummer: 0},
	{ActTochMylti: 0},
	{ActTochBtnBig: 0},
	{ActTochCrestic: 0},
	{ActSoudCell: 0},
	{ActEmptyCellss: 0},
	{Focus: 0},
	{ProgressBlock: 0},
	{ActFrf: 0},
	{SoundAct: 0},
	{Lang_Ynd: 0},
	{lang: 0},
	{screen: 0},
	{itm: 0},
	{Abd: 0},
	{Louder: 0}
];

self.InstanceType = {
	Bagr_Small: class extends self.ISpriteInstance {},
	BagrMenuDown: class extends self.ISpriteInstance {},
	Bagr_Two: class extends self.ISpriteInstance {},
	Bagr_Win: class extends self.ISpriteInstance {},
	Bagr_Help: class extends self.ISpriteInstance {},
	Bagr_PauseLose: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	LocalHost: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Cell_Bagr: class extends self.ISpriteInstance {},
	BagrChoiseCell: class extends self.ISpriteInstance {},
	Cells: class extends self.ISpriteInstance {},
	Cell_Pdl: class extends self.ISpriteInstance {},
	CellsSmall: class extends self.ISpriteInstance {},
	Cell_Point: class extends self.ISpriteInstance {},
	CellPDL: class extends self.ISpriteInstance {},
	Cell_Multy: class extends self.ISpriteInstance {},
	CellsProgress: class extends self.ISpriteInstance {},
	Btn_Pause: class extends self.ISpriteInstance {},
	Btn_Reward: class extends self.ISpriteInstance {},
	Btn_Hummer: class extends self.ISpriteInstance {},
	Btn_Cancel: class extends self.ISpriteInstance {},
	Btn_Multy: class extends self.ISpriteInstance {},
	Btn_Sound: class extends self.ISpriteInstance {},
	Btn_Restart: class extends self.ISpriteInstance {},
	Btn_Crestic: class extends self.ISpriteInstance {},
	Btn_Priz: class extends self.ISpriteInstance {},
	Btn_Start: class extends self.ISpriteInstance {},
	Table_Score: class extends self.ISpriteInstance {},
	Table_Diamonds: class extends self.ISpriteInstance {},
	Table_Sale: class extends self.ISpriteInstance {},
	Table_Pause: class extends self.ISpriteInstance {},
	Table_ReclamaPause: class extends self.ISpriteInstance {},
	Text_Score: class extends self.ITextInstance {},
	Text_Best: class extends self.ITextInstance {},
	Text_Diamonds: class extends self.ITextInstance {},
	Text_Sale: class extends self.ITextInstance {},
	Text_Help: class extends self.ITextInstance {},
	Text_PauseLose: class extends self.ITextInstance {},
	Text_Sound: class extends self.ITextInstance {},
	Text_Restart: class extends self.ITextInstance {},
	Text_PricePriz: class extends self.ITextInstance {},
	Text_Priz: class extends self.ITextInstance {},
	Text_ProgressOne: class extends self.ITextInstance {},
	Text_ProgressTwo: class extends self.ITextInstance {},
	Text_ComBreak: class extends self.ITextInstance {},
	Text_ComBreakRead: class extends self.ITextInstance {},
	Collider_Hummer: class extends self.ISpriteInstance {},
	PDL_Toch: class extends self.ISpriteInstance {},
	Pdl_UIup: class extends self.ISpriteInstance {},
	MyltiPDL: class extends self.ISpriteInstance {},
	ArrayCells: class extends self.IArrayInstance {},
	Сrown: class extends self.ISpriteInstance {},
	Cup: class extends self.ISpriteInstance {},
	Diamonds: class extends self.ISpriteInstance {},
	Hummer: class extends self.ISpriteInstance {},
	LoudTwo: class extends self.ISpriteInstance {},
	Louder_Icon: class extends self.ISpriteInstance {},
	NameGame: class extends self.ISpriteInstance {},
	Finger: class extends self.ISpriteInstance {},
	Btn_Soc: class extends self.ISpriteInstance {},
	Btn_VK: class extends self.ISpriteInstance {},
	BtnEffects: class extends self.ISpriteInstance {},
	Btn_Big: class extends self.ISpriteInstance {}
}