const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.Action_Event1_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Action_Event142_Act2,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.JavaScriptInEvents.Buttons_Event15_Act2,
		C3.JavaScriptInEvents.Buttons_Event24_Act1,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Every,
		C3.JavaScriptInEvents.Start_Event6_Act2,
		C3.JavaScriptInEvents.Start_Event14_Act3,
		C3.JavaScriptInEvents.Start_Event15_Act3
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Sound: 0},
	{LocalHost: 0},
	{Touch: 0},
	{Mouse: 0},
	{Btn_Settings: 0},
	{Btn_Lump: 0},
	{Твинанимация: 0},
	{Btn_Zoom: 0},
	{ID: 0},
	{Act: 0},
	{Name: 0},
	{Btn_Obg: 0},
	{PointBtnObg: 0},
	{Btn_Crestic: 0},
	{Trig: 0},
	{Btn_Next: 0},
	{Btn_Restart: 0},
	{Btn_BackGame: 0},
	{Btn_Priz: 0},
	{Reward: 0},
	{Btn_Start: 0},
	{Bagr: 0},
	{Bagr_Win: 0},
	{BagrLevel: 0},
	{Bagr_Shadow: 0},
	{Bagr_PsLWin: 0},
	{Bagr_Edication: 0},
	{Bagr_Two: 0},
	{Tables_Find: 0},
	{Header_Setting: 0},
	{TableBagr_Setting: 0},
	{Header_Win: 0},
	{Table_ReclamaPause: 0},
	{Text_Find: 0},
	{Text_HeaderSetting: 0},
	{Text_Music: 0},
	{Text_Sound: 0},
	{Text_Win: 0},
	{Text_BackGame: 0},
	{Text_NoTips: 0},
	{Text_Priz: 0},
	{Text_StartMenu: 0},
	{Text_Edic: 0},
	{blueBoxScale: 0},
	{Picters_One: 0},
	{Level_Two: 0},
	{Level_Three: 0},
	{Level_Fore: 0},
	{Level_Five: 0},
	{Level_Sixe: 0},
	{Level_Seven: 0},
	{Level_Eigth: 0},
	{Level_Nine: 0},
	{Level_Ten: 0},
	{Level_Eleven: 0},
	{Level_Twelve: 0},
	{Level_Thirteen: 0},
	{Level_Fourteen: 0},
	{Level_Fifteen: 0},
	{Level_Sixteen: 0},
	{Level_Seventeen: 0},
	{Level_Eighteen: 0},
	{Level_Nineteen: 0},
	{Level_Twentieth: 0},
	{Level_TwentiethOne: 0},
	{Level_TwentiethTwo: 0},
	{Level_TwentiethThree: 0},
	{Level_TwentiethFore: 0},
	{Level_TwentiethFive: 0},
	{Level_TwentiethSixe: 0},
	{Level_TwentiethSeven: 0},
	{Level_TwentiethEigth: 0},
	{Level_TwentiethNine: 0},
	{Level_Thirty: 0},
	{BoolFind: 0},
	{ActToch: 0},
	{ActBtnSloy: 0},
	{NameObg: 0},
	{Find: 0},
	{Watermelon_One: 0},
	{Banana_One: 0},
	{Grapefruit: 0},
	{Kiwi: 0},
	{Grape_Green: 0},
	{Persimmon: 0},
	{Grape_Dark: 0},
	{Strawberry: 0},
	{Cherry: 0},
	{Watermelon_Two: 0},
	{Pineapple: 0},
	{Lemon: 0},
	{Apple: 0},
	{Banana_Two: 0},
	{Peach: 0},
	{Blackberry: 0},
	{Eskimo_One: 0},
	{Candy_One: 0},
	{Candy_Two: 0},
	{Eskimo_Two: 0},
	{Donut_One: 0},
	{Eskimo_Three: 0},
	{Icecream_One: 0},
	{Icecream_Two: 0},
	{Donut_Two: 0},
	{Coconut_One: 0},
	{Coconut_Two: 0},
	{Grilledchicken_One: 0},
	{Watermelon_Three: 0},
	{Tort_One: 0},
	{Box_Fruris: 0},
	{Cocktail_One: 0},
	{Tort_Two: 0},
	{Coffe_One: 0},
	{StakanCoffe: 0},
	{Glove_One: 0},
	{Towel_One: 0},
	{Suitcase_One: 0},
	{Backpack_One: 0},
	{Hat_One: 0},
	{Slippers_One: 0},
	{Sock_One: 0},
	{Towel_Two: 0},
	{Sneakers_One: 0},
	{Hat_Two: 0},
	{Slippers_Two: 0},
	{Towel_Three: 0},
	{Hat_Three: 0},
	{Backpack_Two: 0},
	{Backpack_Three: 0},
	{Galstuk: 0},
	{Slippers_Three: 0},
	{Towel_Fore: 0},
	{Halat_One: 0},
	{Slippers_Fore: 0},
	{Slippers_Five: 0},
	{Backpack_Fore: 0},
	{Sneakers_Two: 0},
	{Vase_One: 0},
	{Fork_One: 0},
	{Pot_One: 0},
	{Vase_Three: 0},
	{Board_One: 0},
	{Vase_Two: 0},
	{Vase_Fore: 0},
	{Vase_Five: 0},
	{Plate_One: 0},
	{Ladle_One: 0},
	{Pot_Two: 0},
	{Grater_One: 0},
	{Bank_One: 0},
	{Bank_Two: 0},
	{Pot_Three: 0},
	{Pot_Fore: 0},
	{Kettle_One: 0},
	{Cupp_One: 0},
	{Cupp_Two: 0},
	{Vase_Sixe: 0},
	{Cupp_Three: 0},
	{Bank_Three: 0},
	{Kettle_Two: 0},
	{Cactus: 0},
	{Flowers_One: 0},
	{Flowers_Two: 0},
	{Flowers_Three: 0},
	{Flowers_Fore: 0},
	{Tree_One: 0},
	{Cactus_Two: 0},
	{Tree_Two: 0},
	{Flowers_Five: 0},
	{Flowers_Sixe: 0},
	{Flowers_Seven: 0},
	{Flowers_Eigth: 0},
	{Flowers_Nine: 0},
	{Flowers_Ten: 0},
	{Flowers_Eleven: 0},
	{Panda_One: 0},
	{Cat_One: 0},
	{Cat_Two: 0},
	{Bird_One: 0},
	{Dog_One: 0},
	{BatterFly_One: 0},
	{Dragonfly: 0},
	{Panda_Two: 0},
	{Panda_Three: 0},
	{Panda_Fore: 0},
	{Camel: 0},
	{Eigle: 0},
	{Gull_One: 0},
	{Sneak_One: 0},
	{Horse_One: 0},
	{Grifon: 0},
	{Bear_Two: 0},
	{Hare_One: 0},
	{Wolf_One: 0},
	{Soroka: 0},
	{Sparrow: 0},
	{Crow: 0},
	{Fish_One: 0},
	{Starfish_One: 0},
	{Starfish_Two: 0},
	{Fish_Two: 0},
	{Jellyfish_One: 0},
	{Fish_Three: 0},
	{Fish_Fore: 0},
	{Box_Wander: 0},
	{Shlem: 0},
	{Almas: 0},
	{Shark: 0},
	{Banka_One: 0},
	{Box_Lily: 0},
	{Lump: 0},
	{Stacan_Brushs: 0},
	{Peper_One: 0},
	{Alarm: 0},
	{Picter_One: 0},
	{Cup_One: 0},
	{Axe_One: 0},
	{Fire_One: 0},
	{Flashlight_One: 0},
	{Binoculars: 0},
	{Sun_Red: 0},
	{Globe: 0},
	{Book_One: 0},
	{Peper_Two: 0},
	{Peper_Three: 0},
	{Box_Yellow: 0},
	{Trushcan_One: 0},
	{Clock_One: 0},
	{Calendar_One: 0},
	{Cup_Two: 0},
	{Cup_Three: 0},
	{Comp_One: 0},
	{Firewood_One: 0},
	{Candle_One: 0},
	{Box_Three: 0},
	{Clock_Two: 0},
	{Star_One: 0},
	{Box_Fore: 0},
	{Box_Five: 0},
	{Venok: 0},
	{Cup_Fore: 0},
	{Branch_One: 0},
	{Clock_Three: 0},
	{Branch_Two: 0},
	{Shkatulka: 0},
	{Pult: 0},
	{Stack: 0},
	{Tent: 0},
	{Mask_One: 0},
	{StacanBrushs_Two: 0},
	{Peper_Fore: 0},
	{Peper_Five: 0},
	{Peper_Sixe: 0},
	{Shield: 0},
	{Spear: 0},
	{Induse: 0},
	{Peper_Seven: 0},
	{Box_Sixe: 0},
	{Glasses_One: 0},
	{Camera_Two: 0},
	{Calendar_Two: 0},
	{Printer_One: 0},
	{Clock_Fore: 0},
	{Clock_Five: 0},
	{Chaiselounge_One: 0},
	{Roulette_One: 0},
	{Valik_One: 0},
	{Peper_Eigth: 0},
	{Drill_One: 0},
	{Mazok_One: 0},
	{Liner_One: 0},
	{Hummer_One: 0},
	{Screwdriver: 0},
	{Shovel_One: 0},
	{Pliers_One: 0},
	{Pliers_Two: 0},
	{Spanner_One: 0},
	{Lump_Two: 0},
	{Toiletpaper_One: 0},
	{Tube_Three: 0},
	{Cup_Five: 0},
	{Tube_Fore: 0},
	{Glasses_Two: 0},
	{Darz: 0},
	{Pen_One: 0},
	{Brush_One: 0},
	{Cup_Sixe: 0},
	{Lump_Three: 0},
	{Brush_Two: 0},
	{Can_One: 0},
	{Savok_One: 0},
	{Gubka_One: 0},
	{Brush_Three: 0},
	{Can_Two: 0},
	{StacanBrushs_Three: 0},
	{Lump_Fore: 0},
	{Raketka_One: 0},
	{Yakor: 0},
	{Airplane_One: 0},
	{Yacht: 0},
	{Car_One: 0},
	{Airplane_Two: 0},
	{Helicopter: 0},
	{Fan: 0},
	{Cleanmachine: 0},
	{BearToy_One: 0},
	{RubberDuck_One: 0},
	{Ball_One: 0},
	{BearToy_Two: 0},
	{Ball_Two: 0},
	{Ball_Three: 0},
	{Ball_Fore: 0},
	{Cube_One: 0},
	{Cube_Two: 0},
	{Ball_Five: 0},
	{Pyramid_One: 0},
	{Cube_Three: 0},
	{Cube_Fore: 0},
	{Cartoy_One: 0},
	{Birdtoy_One: 0},
	{Haretoy_One: 0},
	{Slon_One: 0},
	{Horsetoy_One: 0},
	{Giraffe: 0},
	{Ball_Sixe: 0},
	{Cartoy_Two: 0},
	{lamp_One: 0},
	{lamp_Two: 0},
	{Pillow_One: 0},
	{Pillow_Two: 0},
	{Brash_One: 0},
	{ToiletLid: 0},
	{ToiletBrush_One: 0},
	{ToiletPeper_One: 0},
	{TowelOne: 0},
	{Tube_One: 0},
	{Tube_Two: 0},
	{Tap_One: 0},
	{lamp_Three: 0},
	{Pillow_Three: 0},
	{lamp_Fore: 0},
	{Pillow_Fore: 0},
	{Table_One: 0},
	{Pillow_Five: 0},
	{ArrayNameObg: 0},
	{ArrayBtnObg: 0},
	{ArrayHelp: 0},
	{Поворот: 0},
	{Синусоид: 0},
	{Синусоид2: 0},
	{Confetty: 0},
	{Particles: 0},
	{Rotate: 0},
	{Physics: 0},
	{Cross: 0},
	{Pdl_Win: 0},
	{Cursor: 0},
	{LoudTwo: 0},
	{Louder_Icon: 0},
	{NameGame: 0},
	{Sprite: 0},
	{Finger: 0},
	{FingerTwo: 0},
	{Mouse_One: 0},
	{Btn_Soc: 0},
	{Btn_VK: 0},
	{Btn_Up: 0},
	{Перетаскивание: 0},
	{Picters_Famaly: 0},
	{Obg_Famaly: 0},
	{Btn_RestNext: 0},
	{Btn_Podskazka: 0},
	{Btn_StartMenu: 0},
	{newScale: 0},
	{FindObg: 0},
	{FindObgNow: 0},
	{StepArrayName: 0},
	{StepArrayBtnObg: 0},
	{PointFree: 0},
	{CurrX: 0},
	{CurrY: 0},
	{SizeWith: 0},
	{SizeHeigth: 0},
	{SizeAngel: 0},
	{levt: 0},
	{Level: 0},
	{HelpHint: 0},
	{StepHelp: 0},
	{RndHelp: 0},
	{Zoom: 0},
	{ZoomStep: 0},
	{ArrayBtnObgStep: 0},
	{startDistance: 0},
	{startScale: 0},
	{zoomUID: 0},
	{Education: 0},
	{Vkladla: 0},
	{Music: 0},
	{Priz: 0},
	{PrizTwo: 0},
	{ReklSound: 0},
	{SoundAct: 0},
	{MusicAct: 0},
	{Focus: 0},
	{ActTochBtn: 0},
	{ActZoom: 0},
	{ActTochBlockZoom: 0},
	{ActTochCrestic: 0},
	{ActTochBtnSetting: 0},
	{ActReclama: 0},
	{ActBtnHints: 0},
	{ActBlockBtnHelp: 0},
	{Lang_Ynd: 0},
	{lang: 0},
	{screen: 0},
	{itm: 0},
	{Louder: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	LocalHost: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Btn_Settings: class extends self.ISpriteInstance {},
	Btn_Lump: class extends self.ISpriteInstance {},
	Btn_Zoom: class extends self.ISpriteInstance {},
	Btn_Obg: class extends self.ISpriteInstance {},
	PointBtnObg: class extends self.ISpriteInstance {},
	Btn_Crestic: class extends self.ISpriteInstance {},
	Trig: class extends self.ISpriteInstance {},
	Btn_Next: class extends self.ISpriteInstance {},
	Btn_Restart: class extends self.ISpriteInstance {},
	Btn_BackGame: class extends self.ISpriteInstance {},
	Btn_Priz: class extends self.ISpriteInstance {},
	Reward: class extends self.ISpriteInstance {},
	Btn_Start: class extends self.ISpriteInstance {},
	Bagr: class extends self.ISpriteInstance {},
	Bagr_Win: class extends self.ISpriteInstance {},
	BagrLevel: class extends self.ISpriteInstance {},
	Bagr_Shadow: class extends self.ISpriteInstance {},
	Bagr_PsLWin: class extends self.ISpriteInstance {},
	Bagr_Edication: class extends self.ISpriteInstance {},
	Bagr_Two: class extends self.ISpriteInstance {},
	Tables_Find: class extends self.ISpriteInstance {},
	Header_Setting: class extends self.ISpriteInstance {},
	TableBagr_Setting: class extends self.ISpriteInstance {},
	Header_Win: class extends self.ISpriteInstance {},
	Table_ReclamaPause: class extends self.ISpriteInstance {},
	Text_Find: class extends self.ITextInstance {},
	Text_HeaderSetting: class extends self.ITextInstance {},
	Text_Music: class extends self.ITextInstance {},
	Text_Sound: class extends self.ITextInstance {},
	Text_Win: class extends self.ITextInstance {},
	Text_BackGame: class extends self.ITextInstance {},
	Text_NoTips: class extends self.ITextInstance {},
	Text_Priz: class extends self.ITextInstance {},
	Text_StartMenu: class extends self.ITextInstance {},
	Text_Edic: class extends self.ITextInstance {},
	Picters_One: class extends self.ISpriteInstance {},
	Level_Two: class extends self.ISpriteInstance {},
	Level_Three: class extends self.ISpriteInstance {},
	Level_Fore: class extends self.ISpriteInstance {},
	Level_Five: class extends self.ISpriteInstance {},
	Level_Sixe: class extends self.ISpriteInstance {},
	Level_Seven: class extends self.ISpriteInstance {},
	Level_Eigth: class extends self.ISpriteInstance {},
	Level_Nine: class extends self.ISpriteInstance {},
	Level_Ten: class extends self.ISpriteInstance {},
	Level_Eleven: class extends self.ISpriteInstance {},
	Level_Twelve: class extends self.ISpriteInstance {},
	Level_Thirteen: class extends self.ISpriteInstance {},
	Level_Fourteen: class extends self.ISpriteInstance {},
	Level_Fifteen: class extends self.ISpriteInstance {},
	Level_Sixteen: class extends self.ISpriteInstance {},
	Level_Seventeen: class extends self.ISpriteInstance {},
	Level_Eighteen: class extends self.ISpriteInstance {},
	Level_Nineteen: class extends self.ISpriteInstance {},
	Level_Twentieth: class extends self.ISpriteInstance {},
	Level_TwentiethOne: class extends self.ISpriteInstance {},
	Level_TwentiethTwo: class extends self.ISpriteInstance {},
	Level_TwentiethThree: class extends self.ISpriteInstance {},
	Level_TwentiethFore: class extends self.ISpriteInstance {},
	Level_TwentiethFive: class extends self.ISpriteInstance {},
	Level_TwentiethSixe: class extends self.ISpriteInstance {},
	Level_TwentiethSeven: class extends self.ISpriteInstance {},
	Level_TwentiethEigth: class extends self.ISpriteInstance {},
	Level_TwentiethNine: class extends self.ISpriteInstance {},
	Level_Thirty: class extends self.ISpriteInstance {},
	Watermelon_One: class extends self.ISpriteInstance {},
	Banana_One: class extends self.ISpriteInstance {},
	Grapefruit: class extends self.ISpriteInstance {},
	Kiwi: class extends self.ISpriteInstance {},
	Grape_Green: class extends self.ISpriteInstance {},
	Persimmon: class extends self.ISpriteInstance {},
	Grape_Dark: class extends self.ISpriteInstance {},
	Strawberry: class extends self.ISpriteInstance {},
	Cherry: class extends self.ISpriteInstance {},
	Watermelon_Two: class extends self.ISpriteInstance {},
	Pineapple: class extends self.ISpriteInstance {},
	Lemon: class extends self.ISpriteInstance {},
	Apple: class extends self.ISpriteInstance {},
	Banana_Two: class extends self.ISpriteInstance {},
	Peach: class extends self.ISpriteInstance {},
	Blackberry: class extends self.ISpriteInstance {},
	Eskimo_One: class extends self.ISpriteInstance {},
	Candy_One: class extends self.ISpriteInstance {},
	Candy_Two: class extends self.ISpriteInstance {},
	Eskimo_Two: class extends self.ISpriteInstance {},
	Donut_One: class extends self.ISpriteInstance {},
	Eskimo_Three: class extends self.ISpriteInstance {},
	Icecream_One: class extends self.ISpriteInstance {},
	Icecream_Two: class extends self.ISpriteInstance {},
	Donut_Two: class extends self.ISpriteInstance {},
	Coconut_One: class extends self.ISpriteInstance {},
	Coconut_Two: class extends self.ISpriteInstance {},
	Grilledchicken_One: class extends self.ISpriteInstance {},
	Watermelon_Three: class extends self.ISpriteInstance {},
	Tort_One: class extends self.ISpriteInstance {},
	Box_Fruris: class extends self.ISpriteInstance {},
	Cocktail_One: class extends self.ISpriteInstance {},
	Tort_Two: class extends self.ISpriteInstance {},
	Coffe_One: class extends self.ISpriteInstance {},
	StakanCoffe: class extends self.ISpriteInstance {},
	Glove_One: class extends self.ISpriteInstance {},
	Towel_One: class extends self.ISpriteInstance {},
	Suitcase_One: class extends self.ISpriteInstance {},
	Backpack_One: class extends self.ISpriteInstance {},
	Hat_One: class extends self.ISpriteInstance {},
	Slippers_One: class extends self.ISpriteInstance {},
	Sock_One: class extends self.ISpriteInstance {},
	Towel_Two: class extends self.ISpriteInstance {},
	Sneakers_One: class extends self.ISpriteInstance {},
	Hat_Two: class extends self.ISpriteInstance {},
	Slippers_Two: class extends self.ISpriteInstance {},
	Towel_Three: class extends self.ISpriteInstance {},
	Hat_Three: class extends self.ISpriteInstance {},
	Backpack_Two: class extends self.ISpriteInstance {},
	Backpack_Three: class extends self.ISpriteInstance {},
	Galstuk: class extends self.ISpriteInstance {},
	Slippers_Three: class extends self.ISpriteInstance {},
	Towel_Fore: class extends self.ISpriteInstance {},
	Halat_One: class extends self.ISpriteInstance {},
	Slippers_Fore: class extends self.ISpriteInstance {},
	Slippers_Five: class extends self.ISpriteInstance {},
	Backpack_Fore: class extends self.ISpriteInstance {},
	Sneakers_Two: class extends self.ISpriteInstance {},
	Vase_One: class extends self.ISpriteInstance {},
	Fork_One: class extends self.ISpriteInstance {},
	Pot_One: class extends self.ISpriteInstance {},
	Vase_Three: class extends self.ISpriteInstance {},
	Board_One: class extends self.ISpriteInstance {},
	Vase_Two: class extends self.ISpriteInstance {},
	Vase_Fore: class extends self.ISpriteInstance {},
	Vase_Five: class extends self.ISpriteInstance {},
	Plate_One: class extends self.ISpriteInstance {},
	Ladle_One: class extends self.ISpriteInstance {},
	Pot_Two: class extends self.ISpriteInstance {},
	Grater_One: class extends self.ISpriteInstance {},
	Bank_One: class extends self.ISpriteInstance {},
	Bank_Two: class extends self.ISpriteInstance {},
	Pot_Three: class extends self.ISpriteInstance {},
	Pot_Fore: class extends self.ISpriteInstance {},
	Kettle_One: class extends self.ISpriteInstance {},
	Cupp_One: class extends self.ISpriteInstance {},
	Cupp_Two: class extends self.ISpriteInstance {},
	Vase_Sixe: class extends self.ISpriteInstance {},
	Cupp_Three: class extends self.ISpriteInstance {},
	Bank_Three: class extends self.ISpriteInstance {},
	Kettle_Two: class extends self.ISpriteInstance {},
	Cactus: class extends self.ISpriteInstance {},
	Flowers_One: class extends self.ISpriteInstance {},
	Flowers_Two: class extends self.ISpriteInstance {},
	Flowers_Three: class extends self.ISpriteInstance {},
	Flowers_Fore: class extends self.ISpriteInstance {},
	Tree_One: class extends self.ISpriteInstance {},
	Cactus_Two: class extends self.ISpriteInstance {},
	Tree_Two: class extends self.ISpriteInstance {},
	Flowers_Five: class extends self.ISpriteInstance {},
	Flowers_Sixe: class extends self.ISpriteInstance {},
	Flowers_Seven: class extends self.ISpriteInstance {},
	Flowers_Eigth: class extends self.ISpriteInstance {},
	Flowers_Nine: class extends self.ISpriteInstance {},
	Flowers_Ten: class extends self.ISpriteInstance {},
	Flowers_Eleven: class extends self.ISpriteInstance {},
	Panda_One: class extends self.ISpriteInstance {},
	Cat_One: class extends self.ISpriteInstance {},
	Cat_Two: class extends self.ISpriteInstance {},
	Bird_One: class extends self.ISpriteInstance {},
	Dog_One: class extends self.ISpriteInstance {},
	BatterFly_One: class extends self.ISpriteInstance {},
	Dragonfly: class extends self.ISpriteInstance {},
	Panda_Two: class extends self.ISpriteInstance {},
	Panda_Three: class extends self.ISpriteInstance {},
	Panda_Fore: class extends self.ISpriteInstance {},
	Camel: class extends self.ISpriteInstance {},
	Eigle: class extends self.ISpriteInstance {},
	Gull_One: class extends self.ISpriteInstance {},
	Sneak_One: class extends self.ISpriteInstance {},
	Horse_One: class extends self.ISpriteInstance {},
	Grifon: class extends self.ISpriteInstance {},
	Bear_Two: class extends self.ISpriteInstance {},
	Hare_One: class extends self.ISpriteInstance {},
	Wolf_One: class extends self.ISpriteInstance {},
	Soroka: class extends self.ISpriteInstance {},
	Sparrow: class extends self.ISpriteInstance {},
	Crow: class extends self.ISpriteInstance {},
	Fish_One: class extends self.ISpriteInstance {},
	Starfish_One: class extends self.ISpriteInstance {},
	Starfish_Two: class extends self.ISpriteInstance {},
	Fish_Two: class extends self.ISpriteInstance {},
	Jellyfish_One: class extends self.ISpriteInstance {},
	Fish_Three: class extends self.ISpriteInstance {},
	Fish_Fore: class extends self.ISpriteInstance {},
	Box_Wander: class extends self.ISpriteInstance {},
	Shlem: class extends self.ISpriteInstance {},
	Almas: class extends self.ISpriteInstance {},
	Shark: class extends self.ISpriteInstance {},
	Banka_One: class extends self.ISpriteInstance {},
	Box_Lily: class extends self.ISpriteInstance {},
	Lump: class extends self.ISpriteInstance {},
	Stacan_Brushs: class extends self.ISpriteInstance {},
	Peper_One: class extends self.ISpriteInstance {},
	Alarm: class extends self.ISpriteInstance {},
	Picter_One: class extends self.ISpriteInstance {},
	Cup_One: class extends self.ISpriteInstance {},
	Axe_One: class extends self.ISpriteInstance {},
	Fire_One: class extends self.ISpriteInstance {},
	Flashlight_One: class extends self.ISpriteInstance {},
	Binoculars: class extends self.ISpriteInstance {},
	Sun_Red: class extends self.ISpriteInstance {},
	Globe: class extends self.ISpriteInstance {},
	Book_One: class extends self.ISpriteInstance {},
	Peper_Two: class extends self.ISpriteInstance {},
	Peper_Three: class extends self.ISpriteInstance {},
	Box_Yellow: class extends self.ISpriteInstance {},
	Trushcan_One: class extends self.ISpriteInstance {},
	Clock_One: class extends self.ISpriteInstance {},
	Calendar_One: class extends self.ISpriteInstance {},
	Cup_Two: class extends self.ISpriteInstance {},
	Cup_Three: class extends self.ISpriteInstance {},
	Comp_One: class extends self.ISpriteInstance {},
	Firewood_One: class extends self.ISpriteInstance {},
	Candle_One: class extends self.ISpriteInstance {},
	Box_Three: class extends self.ISpriteInstance {},
	Clock_Two: class extends self.ISpriteInstance {},
	Star_One: class extends self.ISpriteInstance {},
	Box_Fore: class extends self.ISpriteInstance {},
	Box_Five: class extends self.ISpriteInstance {},
	Venok: class extends self.ISpriteInstance {},
	Cup_Fore: class extends self.ISpriteInstance {},
	Branch_One: class extends self.ISpriteInstance {},
	Clock_Three: class extends self.ISpriteInstance {},
	Branch_Two: class extends self.ISpriteInstance {},
	Shkatulka: class extends self.ISpriteInstance {},
	Pult: class extends self.ISpriteInstance {},
	Stack: class extends self.ISpriteInstance {},
	Tent: class extends self.ISpriteInstance {},
	Mask_One: class extends self.ISpriteInstance {},
	StacanBrushs_Two: class extends self.ISpriteInstance {},
	Peper_Fore: class extends self.ISpriteInstance {},
	Peper_Five: class extends self.ISpriteInstance {},
	Peper_Sixe: class extends self.ISpriteInstance {},
	Shield: class extends self.ISpriteInstance {},
	Spear: class extends self.ISpriteInstance {},
	Induse: class extends self.ISpriteInstance {},
	Peper_Seven: class extends self.ISpriteInstance {},
	Box_Sixe: class extends self.ISpriteInstance {},
	Glasses_One: class extends self.ISpriteInstance {},
	Camera_Two: class extends self.ISpriteInstance {},
	Calendar_Two: class extends self.ISpriteInstance {},
	Printer_One: class extends self.ISpriteInstance {},
	Clock_Fore: class extends self.ISpriteInstance {},
	Clock_Five: class extends self.ISpriteInstance {},
	Chaiselounge_One: class extends self.ISpriteInstance {},
	Roulette_One: class extends self.ISpriteInstance {},
	Valik_One: class extends self.ISpriteInstance {},
	Peper_Eigth: class extends self.ISpriteInstance {},
	Drill_One: class extends self.ISpriteInstance {},
	Mazok_One: class extends self.ISpriteInstance {},
	Liner_One: class extends self.ISpriteInstance {},
	Hummer_One: class extends self.ISpriteInstance {},
	Screwdriver: class extends self.ISpriteInstance {},
	Shovel_One: class extends self.ISpriteInstance {},
	Pliers_One: class extends self.ISpriteInstance {},
	Pliers_Two: class extends self.ISpriteInstance {},
	Spanner_One: class extends self.ISpriteInstance {},
	Lump_Two: class extends self.ISpriteInstance {},
	Toiletpaper_One: class extends self.ISpriteInstance {},
	Tube_Three: class extends self.ISpriteInstance {},
	Cup_Five: class extends self.ISpriteInstance {},
	Tube_Fore: class extends self.ISpriteInstance {},
	Glasses_Two: class extends self.ISpriteInstance {},
	Darz: class extends self.ISpriteInstance {},
	Pen_One: class extends self.ISpriteInstance {},
	Brush_One: class extends self.ISpriteInstance {},
	Cup_Sixe: class extends self.ISpriteInstance {},
	Lump_Three: class extends self.ISpriteInstance {},
	Brush_Two: class extends self.ISpriteInstance {},
	Can_One: class extends self.ISpriteInstance {},
	Savok_One: class extends self.ISpriteInstance {},
	Gubka_One: class extends self.ISpriteInstance {},
	Brush_Three: class extends self.ISpriteInstance {},
	Can_Two: class extends self.ISpriteInstance {},
	StacanBrushs_Three: class extends self.ISpriteInstance {},
	Lump_Fore: class extends self.ISpriteInstance {},
	Raketka_One: class extends self.ISpriteInstance {},
	Yakor: class extends self.ISpriteInstance {},
	Airplane_One: class extends self.ISpriteInstance {},
	Yacht: class extends self.ISpriteInstance {},
	Car_One: class extends self.ISpriteInstance {},
	Airplane_Two: class extends self.ISpriteInstance {},
	Helicopter: class extends self.ISpriteInstance {},
	Fan: class extends self.ISpriteInstance {},
	Cleanmachine: class extends self.ISpriteInstance {},
	BearToy_One: class extends self.ISpriteInstance {},
	RubberDuck_One: class extends self.ISpriteInstance {},
	Ball_One: class extends self.ISpriteInstance {},
	BearToy_Two: class extends self.ISpriteInstance {},
	Ball_Two: class extends self.ISpriteInstance {},
	Ball_Three: class extends self.ISpriteInstance {},
	Ball_Fore: class extends self.ISpriteInstance {},
	Cube_One: class extends self.ISpriteInstance {},
	Cube_Two: class extends self.ISpriteInstance {},
	Ball_Five: class extends self.ISpriteInstance {},
	Pyramid_One: class extends self.ISpriteInstance {},
	Cube_Three: class extends self.ISpriteInstance {},
	Cube_Fore: class extends self.ISpriteInstance {},
	Cartoy_One: class extends self.ISpriteInstance {},
	Birdtoy_One: class extends self.ISpriteInstance {},
	Haretoy_One: class extends self.ISpriteInstance {},
	Slon_One: class extends self.ISpriteInstance {},
	Horsetoy_One: class extends self.ISpriteInstance {},
	Giraffe: class extends self.ISpriteInstance {},
	Ball_Sixe: class extends self.ISpriteInstance {},
	Cartoy_Two: class extends self.ISpriteInstance {},
	lamp_One: class extends self.ISpriteInstance {},
	lamp_Two: class extends self.ISpriteInstance {},
	Pillow_One: class extends self.ISpriteInstance {},
	Pillow_Two: class extends self.ISpriteInstance {},
	Brash_One: class extends self.ISpriteInstance {},
	ToiletLid: class extends self.ISpriteInstance {},
	ToiletBrush_One: class extends self.ISpriteInstance {},
	ToiletPeper_One: class extends self.ISpriteInstance {},
	TowelOne: class extends self.ISpriteInstance {},
	Tube_One: class extends self.ISpriteInstance {},
	Tube_Two: class extends self.ISpriteInstance {},
	Tap_One: class extends self.ISpriteInstance {},
	lamp_Three: class extends self.ISpriteInstance {},
	Pillow_Three: class extends self.ISpriteInstance {},
	lamp_Fore: class extends self.ISpriteInstance {},
	Pillow_Fore: class extends self.ISpriteInstance {},
	Table_One: class extends self.ISpriteInstance {},
	Pillow_Five: class extends self.ISpriteInstance {},
	ArrayNameObg: class extends self.IArrayInstance {},
	ArrayBtnObg: class extends self.IArrayInstance {},
	ArrayHelp: class extends self.IArrayInstance {},
	Confetty: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Cross: class extends self.ISpriteInstance {},
	Pdl_Win: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	LoudTwo: class extends self.ISpriteInstance {},
	Louder_Icon: class extends self.ISpriteInstance {},
	NameGame: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Finger: class extends self.ISpriteInstance {},
	FingerTwo: class extends self.ISpriteInstance {},
	Mouse_One: class extends self.ISpriteInstance {},
	Btn_Soc: class extends self.ISpriteInstance {},
	Btn_VK: class extends self.ISpriteInstance {},
	Btn_Up: class extends self.ISpriteInstance {},
	Picters_Famaly: class extends self.ISpriteInstance {},
	Obg_Famaly: class extends self.ISpriteInstance {},
	Btn_RestNext: class extends self.ISpriteInstance {},
	Btn_Podskazka: class extends self.ISpriteInstance {},
	Btn_StartMenu: class extends self.ISpriteInstance {}
}