const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.Action_Event1_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Audio.Acts.SetStereoPan,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.JavaScriptInEvents.Action_Event392_Act1,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.JavaScriptInEvents.Action_Event418_Act1,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.JavaScriptInEvents.Action_Event499_Act42,
		C3.Plugins.System.Cnds.TemplateExists,
		C3.JavaScriptInEvents.Action_Event520_Act2,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.JavaScriptInEvents.Buttons_Event51_Act1,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.JavaScriptInEvents.Start_Event36_Act3,
		C3.JavaScriptInEvents.Start_Event37_Act3,
		C3.JavaScriptInEvents.Inventory_Event1_Act1,
		C3.JavaScriptInEvents.Inventory_Event59_Act1,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.JavaScriptInEvents.Inventory_Event69_Act1,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Sound: 0},
	{LocalHost: 0},
	{Touch: 0},
	{Mouse: 0},
	{Road: 0},
	{StoneOne: 0},
	{StoneThree: 0},
	{StoneTwo: 0},
	{Bagr: 0},
	{Твинанимация: 0},
	{Bagr_Win: 0},
	{Bagr_WinSetting: 0},
	{BagrPointBornZomby: 0},
	{Bagr_Inventory: 0},
	{NameGun: 0},
	{Cell_One: 0},
	{ID: 0},
	{Cell_Progress: 0},
	{CellPdl_Inventary: 0},
	{Btn_Settings: 0},
	{Btn_Pause: 0},
	{Name: 0},
	{Btn_Crestic: 0},
	{Trig: 0},
	{Btn_Home: 0},
	{Btn_Return: 0},
	{Btn_Autogun: 0},
	{Btn_Next: 0},
	{Btn_Stock: 0},
	{Btn_Figth: 0},
	{Btn_HomeInventary: 0},
	{Btn_Reward: 0},
	{Btn_PlayInventary: 0},
	{Price: 0},
	{Act: 0},
	{ActFullupgrade: 0},
	{Btn_Upgrade: 0},
	{Text_HeaderSetting: 0},
	{Text_Music: 0},
	{Text_Sound: 0},
	{Text_Pause: 0},
	{Text_HomeBtn: 0},
	{Text_Resume: 0},
	{Text_Coin: 0},
	{Text_Progress: 0},
	{Text_Wall: 0},
	{Text_Lose: 0},
	{Text_Next: 0},
	{Text_Stock: 0},
	{Text_Nagradfa: 0},
	{Text_Nagrada: 0},
	{Text_UnlockGun: 0},
	{Text_BtnFigth: 0},
	{Text_CoinsInv: 0},
	{Text_Reward: 0},
	{Text_BtnUpgrade: 0},
	{Text_PriceUpgrade: 0},
	{Text_UpgradeMuscle: 0},
	{Text_UpgradeSpeed: 0},
	{Text_WaveCompleted: 0},
	{Table_Setting: 0},
	{Table_Coin: 0},
	{Table_Inventary: 0},
	{Table_Upgrade: 0},
	{Crossbow: 0},
	{Strong: 0},
	{ActHummer: 0},
	{Пуля: 0},
	{Arrow: 0},
	{Mushka: 0},
	{TouchGun: 0},
	{Gun_Progress: 0},
	{Gun: 0},
	{Plr: 0},
	{Bulet: 0},
	{UID_Pdl: 0},
	{Поворот: 0},
	{Peaks: 0},
	{UID_Pickes: 0},
	{PeakPdl: 0},
	{PeakAngel: 0},
	{Прикрепить: 0},
	{Flame_Gun: 0},
	{Hummer: 0},
	{HummerPdl: 0},
	{Boom: 0},
	{ActToch: 0},
	{Grenade: 0},
	{GrenadeAngel: 0},
	{GrenadePdl: 0},
	{BN: 0},
	{BoomPDL: 0},
	{Line: 0},
	{Line_Bagr: 0},
	{LineUpgrade_Grey: 0},
	{WithLine: 0},
	{NameLine: 0},
	{LineUpgrade_Green: 0},
	{Musle: 0},
	{LineUpgrade_Yellow: 0},
	{Life: 0},
	{ActCrash: 0},
	{DeadWall: 0},
	{ActBoom: 0},
	{Reward: 0},
	{id: 0},
	{Zombie_One: 0},
	{BornZombyPoint: 0},
	{Shadow: 0},
	{Zombie_UID: 0},
	{ZombieOne_Shadow: 0},
	{LineZombi_Bagr: 0},
	{PointZombie: 0},
	{StrongLife: 0},
	{LineZombi_Red: 0},
	{Uid_Zombei: 0},
	{PointStopZombie: 0},
	{ZombiesMove: 0},
	{LineZombi_Yellow: 0},
	{Wall: 0},
	{WallColl: 0},
	{value: 0},
	{coin_balls: 0},
	{Синусоида: 0},
	{Синусоида2: 0},
	{NameGame: 0},
	{ArrayRnd: 0},
	{LineZomby: 0},
	{Bagr_Two: 0},
	{LoudTwo: 0},
	{Синусоид: 0},
	{Louder_Icon: 0},
	{Finger: 0},
	{Bagr_Edication: 0},
	{Text_Edic: 0},
	{Btn_Soc: 0},
	{Btn_VK: 0},
	{Btn_Up: 0},
	{Btn_Ps: 0},
	{Zombie_Famaly: 0},
	{Gun_Famaly: 0},
	{RndIDZombieAnim: 0},
	{Music: 0},
	{Wave: 0},
	{Coins: 0},
	{Priz: 0},
	{PrizTwo: 0},
	{ReklSound: 0},
	{Education: 0},
	{EducationInv: 0},
	{EducationTwo: 0},
	{Vkladla: 0},
	{WallLife: 0},
	{WallDead: 0},
	{WallUpdate: 0},
	{WallZomdiesToch: 0},
	{ArrowUpdate: 0},
	{ArrowSpeedShuting: 0},
	{PeakUpdate: 0},
	{PeakSpeedShuting: 0},
	{ActPeak_UnBlock: 0},
	{HummerUpdate: 0},
	{ActHummer_UnBlock: 0},
	{ActHummer_Preletel: 0},
	{ActHummer_BlockTochZombie: 0},
	{HummerSpeedShuting: 0},
	{GunUpdate: 0},
	{ActGun_UnBlock: 0},
	{GunSpeedShuting: 0},
	{GunAngelOne: 0},
	{GrenadeUpdate: 0},
	{ActGrenade_UnBlock: 0},
	{GrenadeSpeedShuting: 0},
	{GunName: 0},
	{StopGun: 0},
	{Inventare_GunName: 0},
	{Step_BtnUpg: 0},
	{StepYelloOne: 0},
	{Inventare_Speed: 0},
	{Inventare_SpeedYellow: 0},
	{Inventare_Musle: 0},
	{Inventare_MusleYellow: 0},
	{ArrowSpeed_Inv: 0},
	{ArrowMusle_Inv: 0},
	{SoundHummer: 0},
	{SpeedZombie: 0},
	{TimeBornZombe: 0},
	{NowZombyBorn: 0},
	{RndBornZomby: 0},
	{RndBornZombyID: 0},
	{RndBornZombyID_Two: 0},
	{ZombiesOnMonitor: 0},
	{Nagrada: 0},
	{DellZomby: 0},
	{DellZombyNow: 0},
	{RndID_Zombie: 0},
	{RndBornZombieTwo: 0},
	{BornNowZombie: 0},
	{DellZombyTwo: 0},
	{ActRndTwo: 0},
	{Line_With: 0},
	{Line_WithStep: 0},
	{ActTochBtn: 0},
	{CresticAct: 0},
	{SoundAct: 0},
	{MusicAct: 0},
	{ActInduction: 0},
	{Act_ZombiesTouchWall: 0},
	{Focus: 0},
	{ActWin: 0},
	{ActReclama: 0},
	{Lang_Ynd: 0},
	{lang: 0},
	{screen: 0},
	{itm: 0},
	{Speed: 0},
	{SpeedYellow: 0},
	{MusleYellow: 0},
	{StepYellow: 0},
	{WaveText: 0},
	{Louder: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	LocalHost: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Road: class extends self.ITiledBackgroundInstance {},
	StoneOne: class extends self.ISpriteInstance {},
	StoneThree: class extends self.ISpriteInstance {},
	StoneTwo: class extends self.ISpriteInstance {},
	Bagr: class extends self.ISpriteInstance {},
	Bagr_Win: class extends self.ISpriteInstance {},
	Bagr_WinSetting: class extends self.ISpriteInstance {},
	BagrPointBornZomby: class extends self.ISpriteInstance {},
	Bagr_Inventory: class extends self.ISpriteInstance {},
	Cell_One: class extends self.ISpriteInstance {},
	Cell_Progress: class extends self.ISpriteInstance {},
	CellPdl_Inventary: class extends self.ISpriteInstance {},
	Btn_Settings: class extends self.ISpriteInstance {},
	Btn_Pause: class extends self.ISpriteInstance {},
	Btn_Crestic: class extends self.ISpriteInstance {},
	Trig: class extends self.ISpriteInstance {},
	Btn_Home: class extends self.ISpriteInstance {},
	Btn_Return: class extends self.ISpriteInstance {},
	Btn_Autogun: class extends self.ISpriteInstance {},
	Btn_Next: class extends self.ISpriteInstance {},
	Btn_Stock: class extends self.ISpriteInstance {},
	Btn_Figth: class extends self.ISpriteInstance {},
	Btn_HomeInventary: class extends self.ISpriteInstance {},
	Btn_Reward: class extends self.ISpriteInstance {},
	Btn_PlayInventary: class extends self.ISpriteInstance {},
	Btn_Upgrade: class extends self.ISpriteInstance {},
	Text_HeaderSetting: class extends self.ITextInstance {},
	Text_Music: class extends self.ITextInstance {},
	Text_Sound: class extends self.ITextInstance {},
	Text_Pause: class extends self.ITextInstance {},
	Text_HomeBtn: class extends self.ITextInstance {},
	Text_Resume: class extends self.ITextInstance {},
	Text_Coin: class extends self.ITextInstance {},
	Text_Progress: class extends self.ITextInstance {},
	Text_Wall: class extends self.ITextInstance {},
	Text_Lose: class extends self.ITextInstance {},
	Text_Next: class extends self.ITextInstance {},
	Text_Stock: class extends self.ITextInstance {},
	Text_Nagradfa: class extends self.ITextInstance {},
	Text_Nagrada: class extends self.ITextInstance {},
	Text_UnlockGun: class extends self.ITextInstance {},
	Text_BtnFigth: class extends self.ITextInstance {},
	Text_CoinsInv: class extends self.ITextInstance {},
	Text_Reward: class extends self.ITextInstance {},
	Text_BtnUpgrade: class extends self.ITextInstance {},
	Text_PriceUpgrade: class extends self.ITextInstance {},
	Text_UpgradeMuscle: class extends self.ITextInstance {},
	Text_UpgradeSpeed: class extends self.ITextInstance {},
	Text_WaveCompleted: class extends self.ITextInstance {},
	Table_Setting: class extends self.ISpriteInstance {},
	Table_Coin: class extends self.ISpriteInstance {},
	Table_Inventary: class extends self.ISpriteInstance {},
	Table_Upgrade: class extends self.ISpriteInstance {},
	Crossbow: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Mushka: class extends self.ISpriteInstance {},
	TouchGun: class extends self.ISpriteInstance {},
	Gun_Progress: class extends self.ISpriteInstance {},
	Gun: class extends self.ISpriteInstance {},
	Bulet: class extends self.ISpriteInstance {},
	Peaks: class extends self.ISpriteInstance {},
	PeakPdl: class extends self.ISpriteInstance {},
	PeakAngel: class extends self.ISpriteInstance {},
	Flame_Gun: class extends self.ISpriteInstance {},
	Hummer: class extends self.ISpriteInstance {},
	HummerPdl: class extends self.ISpriteInstance {},
	Boom: class extends self.ISpriteInstance {},
	Grenade: class extends self.ISpriteInstance {},
	GrenadeAngel: class extends self.ISpriteInstance {},
	GrenadePdl: class extends self.ISpriteInstance {},
	BN: class extends self.ISpriteInstance {},
	BoomPDL: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Line_Bagr: class extends self.ISpriteInstance {},
	LineUpgrade_Grey: class extends self.ISpriteInstance {},
	LineUpgrade_Green: class extends self.ISpriteInstance {},
	LineUpgrade_Yellow: class extends self.ISpriteInstance {},
	Zombie_One: class extends self.ISpriteInstance {},
	BornZombyPoint: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	ZombieOne_Shadow: class extends self.ISpriteInstance {},
	LineZombi_Bagr: class extends self.ISpriteInstance {},
	PointZombie: class extends self.ISpriteInstance {},
	LineZombi_Red: class extends self.ISpriteInstance {},
	PointStopZombie: class extends self.ISpriteInstance {},
	ZombiesMove: class extends self.ISpriteInstance {},
	LineZombi_Yellow: class extends self.ISpriteInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	WallColl: class extends self.ISpriteInstance {},
	coin_balls: class extends self.ISpriteInstance {},
	NameGame: class extends self.ISpriteInstance {},
	ArrayRnd: class extends self.IArrayInstance {},
	LineZomby: class extends self.ISpriteInstance {},
	Bagr_Two: class extends self.ISpriteInstance {},
	LoudTwo: class extends self.ISpriteInstance {},
	Louder_Icon: class extends self.ISpriteInstance {},
	Finger: class extends self.ISpriteInstance {},
	Bagr_Edication: class extends self.ISpriteInstance {},
	Text_Edic: class extends self.ITextInstance {},
	Btn_Soc: class extends self.ISpriteInstance {},
	Btn_VK: class extends self.ISpriteInstance {},
	Btn_Up: class extends self.ISpriteInstance {},
	Btn_Ps: class extends self.ISpriteInstance {},
	Zombie_Famaly: class extends self.ISpriteInstance {},
	Gun_Famaly: class extends self.ISpriteInstance {}
}