const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.Action_Event1_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.ScriptsInEvents.Action_Event45_Act1,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.ScriptsInEvents.Action_Event58_Act1,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.ScriptsInEvents.Action_Event66_Act1,
		C3.ScriptsInEvents.Action_Event68_Act1,
		C3.Plugins.System.Cnds.Compare,
		C3.ScriptsInEvents.Action_Event73_Act1,
		C3.ScriptsInEvents.Action_Event78_Act1,
		C3.ScriptsInEvents.Action_Event83_Act1,
		C3.ScriptsInEvents.Action_Event88_Act1,
		C3.ScriptsInEvents.Action_Event93_Act1,
		C3.ScriptsInEvents.Action_Event98_Act1,
		C3.ScriptsInEvents.Action_Event103_Act1,
		C3.ScriptsInEvents.Action_Event108_Act1,
		C3.ScriptsInEvents.Action_Event113_Act1,
		C3.ScriptsInEvents.Action_Event118_Act1,
		C3.ScriptsInEvents.Action_Event123_Act1,
		C3.ScriptsInEvents.Action_Event128_Act1,
		C3.ScriptsInEvents.Action_Event133_Act1,
		C3.ScriptsInEvents.Action_Event138_Act1,
		C3.ScriptsInEvents.Action_Event143_Act1,
		C3.ScriptsInEvents.Action_Event151_Act1,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.ScriptsInEvents.Action_Event158_Act1,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.ScriptsInEvents.Buttons_Event43_Act2,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.ScriptsInEvents.Start_Event15_Act3,
		C3.ScriptsInEvents.Start_Event16_Act3
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Sound: 0},
	{LocalHost: 0},
	{Touch: 0},
	{Bagr_Small: 0},
	{Bagr_Two: 0},
	{BagrMenuDown: 0},
	{MenuBagrUP: 0},
	{ActionBagr: 0},
	{BagrNumAction: 0},
	{Твинанимация: 0},
	{Bagr_Win: 0},
	{Bagr_Help: 0},
	{Bagr_PauseLose: 0},
	{Btn_Pause: 0},
	{Btn_Reward: 0},
	{Btn_Hummer: 0},
	{Btn_Multy: 0},
	{ID: 0},
	{Btn_Priz: 0},
	{Btn_Crestic: 0},
	{Btn_Restart: 0},
	{Btn_Sound: 0},
	{Text_Best: 0},
	{Text_Score: 0},
	{Text_Diamonds: 0},
	{Text_Sale: 0},
	{Text_Help: 0},
	{Text_PricePriz: 0},
	{Text_Priz: 0},
	{Text_PauseLose: 0},
	{Text_ProgressOne: 0},
	{Text_ProgressTwo: 0},
	{Text_Restart: 0},
	{Text_Sound: 0},
	{Text_ComBreak: 0},
	{Text_ComBreakRead: 0},
	{Table_Score: 0},
	{Table_Diamonds: 0},
	{Bit: 0},
	{NameIcon: 0},
	{Table_Sale: 0},
	{Table_Pause: 0},
	{Table_ReclamaPause: 0},
	{number: 0},
	{row: 0},
	{line: 0},
	{ActFind: 0},
	{ActToch: 0},
	{curY: 0},
	{ActDown: 0},
	{NumDown: 0},
	{Tween: 0},
	{Number: 0},
	{Btn_BlockBagr: 0},
	{Act: 0},
	{Row: 0},
	{Line: 0},
	{Var: 0},
	{NumPoint: 0},
	{Num_Multy: 0},
	{Ver: 0},
	{NumberProgress: 0},
	{ArrayNum: 0},
	{Collider_Hummer: 0},
	{PDL_Toch: 0},
	{Collider_Multy: 0},
	{Спрайт: 0},
	{Сrown: 0},
	{Cup: 0},
	{Diamonds: 0},
	{Hummer: 0},
	{Поворот: 0},
	{LoudTwo: 0},
	{Синусоид: 0},
	{Louder_Icon: 0},
	{Btn_Start: 0},
	{NameGame: 0},
	{Btn_Soc: 0},
	{Btn_VK: 0},
	{BtnEffects: 0},
	{Btn_Big: 0},
	{num: 0},
	{Priz: 0},
	{PrizTwo: 0},
	{ReklSound: 0},
	{Vkladla: 0},
	{RndStart: 0},
	{RndEnd: 0},
	{RndVar: 0},
	{RndVarBigCell: 0},
	{Education: 0},
	{NumRow: 0},
	{NumLine: 0},
	{Score: 0},
	{RecordScore: 0},
	{numCombo: 0},
	{NumVar: 0},
	{CurY: 0},
	{CurX: 0},
	{ProgressOne: 0},
	{ProgressTwo: 0},
	{ProgressCelD: 0},
	{BtnBlock: 0},
	{ActBlockNum: 0},
	{ActAssing: 0},
	{ActTochHummer: 0},
	{ActTochMylti: 0},
	{ActTochCrestic: 0},
	{ActTochBtnBig: 0},
	{Focus: 0},
	{ProgressBlock: 0},
	{ActTimer: 0},
	{SoundAct: 0},
	{Lang_Ynd: 0},
	{lang: 0},
	{screen: 0},
	{itm: 0},
	{Abd: 0},
	{Louder: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	LocalHost: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Bagr_Small: class extends self.ISpriteInstance {},
	Bagr_Two: class extends self.ISpriteInstance {},
	BagrMenuDown: class extends self.ISpriteInstance {},
	MenuBagrUP: class extends self.ISpriteInstance {},
	ActionBagr: class extends self.ISpriteInstance {},
	BagrNumAction: class extends self.ISpriteInstance {},
	Bagr_Win: class extends self.ISpriteInstance {},
	Bagr_Help: class extends self.ISpriteInstance {},
	Bagr_PauseLose: class extends self.ISpriteInstance {},
	Btn_Pause: class extends self.ISpriteInstance {},
	Btn_Reward: class extends self.ISpriteInstance {},
	Btn_Hummer: class extends self.ISpriteInstance {},
	Btn_Multy: class extends self.ISpriteInstance {},
	Btn_Priz: class extends self.ISpriteInstance {},
	Btn_Crestic: class extends self.ISpriteInstance {},
	Btn_Restart: class extends self.ISpriteInstance {},
	Btn_Sound: class extends self.ISpriteInstance {},
	Text_Best: class extends self.ITextInstance {},
	Text_Score: class extends self.ITextInstance {},
	Text_Diamonds: class extends self.ITextInstance {},
	Text_Sale: class extends self.ITextInstance {},
	Text_Help: class extends self.ITextInstance {},
	Text_PricePriz: class extends self.ITextInstance {},
	Text_Priz: class extends self.ITextInstance {},
	Text_PauseLose: class extends self.ITextInstance {},
	Text_ProgressOne: class extends self.ITextInstance {},
	Text_ProgressTwo: class extends self.ITextInstance {},
	Text_Restart: class extends self.ITextInstance {},
	Text_Sound: class extends self.ITextInstance {},
	Text_ComBreak: class extends self.ITextInstance {},
	Text_ComBreakRead: class extends self.ITextInstance {},
	Table_Score: class extends self.ISpriteInstance {},
	Table_Diamonds: class extends self.ISpriteInstance {},
	Table_Sale: class extends self.ISpriteInstance {},
	Table_Pause: class extends self.ISpriteInstance {},
	Table_ReclamaPause: class extends self.ISpriteInstance {},
	Number: class extends self.ISpriteInstance {},
	Btn_BlockBagr: class extends self.ISpriteInstance {},
	NumPoint: class extends self.ISpriteInstance {},
	Num_Multy: class extends self.ISpriteInstance {},
	NumberProgress: class extends self.ISpriteInstance {},
	ArrayNum: class extends self.IArrayInstance {},
	Collider_Hummer: class extends self.ISpriteInstance {},
	PDL_Toch: class extends self.ISpriteInstance {},
	Collider_Multy: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Сrown: class extends self.ISpriteInstance {},
	Cup: class extends self.ISpriteInstance {},
	Diamonds: class extends self.ISpriteInstance {},
	Hummer: class extends self.ISpriteInstance {},
	LoudTwo: class extends self.ISpriteInstance {},
	Louder_Icon: class extends self.ISpriteInstance {},
	Btn_Start: class extends self.ISpriteInstance {},
	NameGame: class extends self.ISpriteInstance {},
	Btn_Soc: class extends self.ISpriteInstance {},
	Btn_VK: class extends self.ISpriteInstance {},
	BtnEffects: class extends self.ISpriteInstance {},
	Btn_Big: class extends self.ISpriteInstance {}
}